JuliaArrays/StaticArrays.jl

- src/StaticArrays.jl
- src/arraymath.jl
Also turns on precompilation (hope that's OK!).
> Non-allocating fill

- src/core.jl
- src/matrix_multiply.jl
- test/matrix_multiply.jl
This needs to test (tests don't finish on my Windows machine...)
> Speedier AbstractArray conversion

- src/arraymath.jl
- test/arraymath.jl
> Add zero function

- src/linalg.jl
- test/linalg.jl
Also a couple of minimal tests for normalize and vecnorm
Addresses part of #45
> Fast path for commonly used version of normalize()

- perf/bench9.txt
- perf/benchmark3.jl
- src/SizedArray.jl
- src/abstractarray.jl
- src/cholesky.jl
- src/eigen.jl
- src/inv.jl
- src/matrix_multiply.jl
- test/abstractarray.jl
- test/eigen.jl
- test/matrix_multiply.jl
- test/runtests.jl
Begin implementing use of `Size` where it makes sense ,and related changes.
Also added some *BenchmarkTools.jl* performance tests (get unusual results).
> Use `Size` more consistently

- README.md
@SimonDanisch @c42f I wasn't sure exactly how to word this... opinions?
> Added a message regarding moving forward with StaticArrays

- src/mapreduce.jl
- test/mapreduce.jl
Seems to just be a typo. :)
This is my first pull request, so hopefully I did it correctly.
> Fix definition of prod()

- src/indexing.jl
- test/indexing.jl
Two pirates walk into a bar dragging a heavy chest.
As they open it the barman reels back in horror, glimpsing the unchanging rectangular pattern inside.
"Get out you filthy scum, we don't serve your type of pirates here"
Resolves #101
> Remove indexing of AbstractArray with Tuple

- src/FieldVector.jl
- src/MMatrix.jl
- src/MVector.jl
- src/SArray.jl
- src/SMatrix.jl
- src/SVector.jl
- test/FieldVector.jl
> Clean up and fix pointer code

- src/StaticArrays.jl
- src/expm.jl
- test/expm.jl
- test/runtests.jl
Same as #160, but to master branch
> Add matrix exponential for 1x1 and 2x2, and fallback to Base

- src/linalg.jl
- test/linalg.jl
Didn't actually work for complex arrays...
> Fix ctranspose bug & add test

- src/eigen.jl
- test/eigen.jl
Fixed some bugs along the way...
> Let eigen work for "big" Herm/symm matrices

- test/MArray.jl
Didn't do `rand!` because it has some weird ambiguity I don't understand.
> Add tests for randn! and randexp!

- test/core.jl
I left two commented out bc they error and I'm not super sure why
> Uncomment more convert tests

- test/broadcast.jl
- test/runtests.jl
> Forgot to include broadcast.jl in runtests in #196

- src/FixedSizeArrays.jl
- test/fixed_size_arrays.jl
fixes #202 
(I am assuming that the current behavior is actually a bug; please let me know if it's not)
> RFC: fix construction of FSA types with heterogeneous types

- src/mapreduce.jl
- test/mapreduce.jl
Since I derped in #209 i fixed it :) 
fix #209
> inline sum(f::Callable, a::StaticArray)

- src/MArray.jl
- src/SArray.jl
- src/SizedArray.jl
- src/StaticArrays.jl
- src/abstractarray.jl
- test/MArray.jl
- test/SArray.jl
- test/SizedArray.jl
- test/abstractarray.jl
> Implement promote_rule for StaticArray to mirror Base.Array

- src/expm.jl
- test/expm.jl
Extends @Godisemo 's code to the complex case.
> Add complex matrix exponential for 2x2

- src/det.jl
- test/det.jl
The infrastructure can easily be extended for ``logdetabs`` and others. 
Please check that I am doing the double interpolation ``$($f)`` correctly.
> Add logdet

- .travis.yml
- appveyor.yml
- src/broadcast.jl
- test/broadcast.jl
> Fix broadcast with empty arrays

- src/arraymath.jl
- test/MArray.jl
- test/MMatrix.jl
- test/MVector.jl
- test/SArray.jl
- test/SDiagonal.jl
- test/SMatrix.jl
- test/SVector.jl
- test/arraymath.jl
- test/linalg.jl
That `convert` test is dying :( but only on `nightly` I guess
> Add error tests

- src/abstractarray.jl
> copy preserves type

- src/abstractarray.jl
- test/abstractarray.jl
> Fix bug for sizedarray_similar_type, more tests

- src/eigen.jl
- test/eigen.jl
The 1x1 complex matrix case wasn't being handled right ... this eigenvalue is very easy to compute :p.
Added in more tests for an untouched code branch.
> Even more eigfact fun

- src/arraymath.jl
- test/arraymath.jl
> fix rand(::StaticArray)

- src/arraymath.jl
Note: PR against documenter-deploy-fixes.
Fix the doctest issue.
> Fix doctest for arithmetic_closure.

- docs/make.jl
- src/arraymath.jl
Attempt at fixing automated doc deployment. See #298
> Small tweaks to get doc deployment working

- src/solve.jl
- test/solve.jl
... and I was puzzling what my code does wrong.
> Fix bug in 1x1 solve

- src/FixedSizeArrays.jl
- test/fixed_size_arrays.jl
> remove a broken convert() method and test that it was unnecessary

- src/MArray.jl
> MArray documentation - can be mutated

- src/MArray.jl
- src/MMatrix.jl
- src/MVector.jl
- src/util.jl
Ref: https://github.com/JuliaLang/julia/pull/25362.
> Adapt to Base.data_pointer_from_objref removal

- src/indexing.jl
- test/indexing.jl
Noticed while working on #368.
> Fix indexing empty arrays

- REQUIRE
- src/SizedArray.jl
- src/broadcast.jl
- src/mapreduce.jl
- test/Scalar.jl
Not the most pressing issue for 0.7, but one with a simple solution.
> Replace `uninitialized` with `undef`

- src/deque.jl
> Fix a missing propagate_inbounds in setindex

- src/SDiagonal.jl
- src/StaticArrays.jl
- src/abstractarray.jl
- src/broadcast.jl
- src/eigen.jl
- src/indexing.jl
- src/linalg.jl
- src/lyap.jl
- src/mapreduce.jl
- test/SDiagonal.jl
- test/indexing.jl
- test/linalg.jl
- test/runtests.jl
* Handle various deprecations
* Improve broadcasting over types on v0.7
> Fix some v0.7 issues

- src/broadcast.jl
Note: this is a PR against sd/lazybcast, not against master!
The fallback is covered by the following test set:
https://github.com/JuliaArrays/StaticArrays.jl/blob/9d80122dabf420373a0c3a0db09b52a2b8df8089/test/broadcast.jl#L170-L183
which did indeed catch an error due to the fact that the `axes` field was not being copied to the `Broadcasted{DefaultArrayStyle{M}}` (which has already been set to `axes(dest)` in `materialize!`  at this point and is needed for `copyto!` to work correctly). Using the available `convert` method fixes the issue.
I also reduced code duplication a bit and removed the fallback changes in `Base.copy`; this can be done in a separate PR, and with the new broadcast API the commented-out code is not the correct way to do it.
> Fixes to fallback to generic broadcast!.

- src/MArray.jl
- src/MMatrix.jl
- src/MVector.jl
- src/SArray.jl
- src/SMatrix.jl
- src/SVector.jl
See https://github.com/JuliaLang/julia/pull/27098.
> Adapt to eval change (Julia PR 27098)

- src/lyap.jl
- src/mapreduce.jl
- test/linalg.jl
- test/matrix_multiply.jl
- test/runtests.jl
Everything except `qr.jl` and `fixed_size_arrays.jl` passes on master now. See commit messages. I fixed some depwarns too, but there are still a few remaining.
> Another round of fixes

- test/SizedArray.jl
This test is missing and I checked with `@which` that my test calls the missing line 60 in `SizedArray.jl`.
> Test convert(::Array, ::SizedArray)

- src/traits.jl
- test/core.jl
> Fix helpful warning on Julia 1.x

- src/broadcast.jl
Based on https://github.com/JuliaLang/julia/pull/29843/files#diff-8e941cd1878722cc12a54e01537b8e18R142.
> Fix #538, BroadcastStyle broken on Julia master.

- src/indexing.jl
- test/indexing.jl
> Fix setindex with vector indices

- src/StaticArrays.jl
- src/abstractarray.jl
- test/abstractarray.jl
> Add reverse(::SVector), with tests.

- test/runtests.jl
This draws a red line in the sand with regards to #18.
> Read my lips: no new ambiguities

- docs/src/pages/api.md
Fix #501 
This is #502, but with the tweaks I suggested over there to avoid the average user accidentally invoking undefined behavior.
CC @chethega
Closes #502
> Fix docs for reinterpret

- src/expm.jl
- test/expm.jl
See https://github.com/JuliaArrays/StaticArrays.jl/issues/623
> Avoid division by 0 in 2x2 complex exp

- README.md
These have been dead for more than a year.
(My small part in the ongoing spring cleaning).
> get rid of PkgEval badges

- src/broadcast.jl
- test/broadcast.jl
I think this looks more or less right.
> Broadcasting with tuples (fixes #485)

- src/mapreduce.jl
- test/mapreduce.jl
- test/runtests.jl
Just two methods for disambiguation.
> fix for issue #641

- .travis.yml
- appveyor.yml
As mentioned at https://github.com/JuliaArrays/StaticArrays.jl/pull/672#issuecomment-542912287 CC @fredrikekre
> Allow CI for release branches

- .travis.yml
- appveyor.yml
I just noticed this was missing. Hopefully there will be no problems given we pass tests on nightly...
> Enable CI with julia-1.3

- src/eigen.jl
- test/eigen.jl
- test/testutil.jl
I've added a method for generalized eigenvalues of two static matrices. We need that in Manifolds.jl and currently we do type piracy to get that.
> Generalized eigenvalues of two static matrices

- src/indexing.jl
- test/indexing.jl
> Views of zero-dimensional arrays

- src/MMatrix.jl
- src/MVector.jl
I fixed MArray in #711, but missed these.
> add undef tags to docs for MMatrix and MVector

- src/eigen.jl
Addresses #696 by implementing the iterative method presented in https://www.geometrictools.com/Documentation/RobustEigenSymmetric3x3.pdf for 3x3 symmetric eigen analysis.
> WIP: Improve precision of 3x3 eigen analysis

- benchmark/bench_qr.jl
- benchmark/benchmarks.jl
ref https://github.com/JuliaArrays/StaticArrays.jl/pull/736#discussion_r381161478
I think it's better to merge this after #737.
> Use const for suite

- src/linalg.jl
- test/linalg.jl
> Fix convert(::Type{<:StaticArray}, ::UniformScaling)

- test/ambiguities.jl
> [test] set version specific bounds in detect_ambiguities

- src/SizedArray.jl
- test/SizedArray.jl
> Pointer method for SizedArray

- src/abstractarray.jl
- test/abstractarray.jl
- test/matrix_multiply.jl
> Making similar_type check inside array wrappers

- .github/workflows/TagBot.yml
As documented at https://discourse.julialang.org/t/ann-required-updates-to-tagbot-yml/49249
> Update to event-driven TagBot.yml

- src/cholesky.jl
- test/chol.jl
> Inverse of Cholesky decomposition

- Project.toml
I'm excited to get @chriselrod 's new cholesky-check work, what do folks think about making a new release?
> Version 1.1.0

- Project.toml
- src/SDiagonal.jl
- test/SDiagonal.jl
This now allows
```julia
julia> zero(Diagonal{Int, SVector{2,Int}})
2×2 Diagonal{Int64, SVector{2, Int64}}:
0  ⋅
⋅  0
julia> zeros(Diagonal{Int, SVector{2,Int}}, 3)
3-element Vector{Diagonal{Int64, SVector{2, Int64}}}:
[0 0; 0 0]
[0 0; 0 0]
[0 0; 0 0]
```
> Add zero(::Type{<:SDiagonal})

- Project.toml
- src/abstractarray.jl
- test/abstractarray.jl
Fixes #947
But one case doesn't work, and I didn't understand why yet.
> Add `reshape` methods

- Project.toml
- src/linalg.jl
- test/linalg.jl
This should remove the type piracy reported in #961 .
> Fix issue #961

- Project.toml
- src/abstractarray.jl
- test/abstractarray.jl
This should fix part of the problem reported in #981 .
> Make `vec` just return the argument for `MVector` and `SizedVector`.

- Project.toml
- src/mapreduce.jl
> Force more inlining of `reduce`

- Project.toml
- src/deque.jl
- test/deque.jl
> Fix insert to 0-length SVector

- src/traits.jl
> Update docstring of `Size`

- Project.toml
See https://github.com/JuliaArrays/StaticArrays.jl/commit/5dfbe09133adda06f057217197520c50a61460e4#commitcomment-75230737 .
> Bump version to 1.4.5

- README.md
- src/deque.jl
- test/deque.jl
Closes https://github.com/JuliaArrays/StaticArrays.jl/issues/1033.
> Implement Base.setindex with CartesianIndex

- Project.toml
x-ref https://github.com/JuliaArrays/StaticArrays.jl/pull/1034#issuecomment-1146628633
> Bump version to `v1.4.6`

- Project.toml
- src/convert.jl
Reported here: https://github.com/JuliaArrays/StaticArrays.jl/issues/1047
Ref: https://github.com/JuliaLabs/Cassette.jl/issues/198
> Workaround for has_size Cassette issue

- Project.toml
- src/StaticArrays.jl
> Export StaticArraysCore (fixes #1061)

- Project.toml
- src/broadcast.jl
> remove ambiguous copyto! method

- test/testutil.jl
see https://github.com/JuliaLang/julia/pull/41616
> Fix `@test_inlined` on nightly

- Project.toml
- src/mapreduce.jl
- test/mapreduce.jl
> Fix reduction over empty array

- Project.toml
- src/linalg.jl
- test/runtests.jl
- test/unitful.jl
This should fix #1124. I'm not sure how to easily make a test for that, probably making Unitful.jl a test dependency?
> Fix norm of unitful quantities

- Project.toml
- src/linalg.jl
- test/unitful.jl
> Fix norm of unitful zero vector

- Project.toml
- src/mapreduce.jl
- test/mapreduce.jl
> Fix returned value of `map!`

- docs/src/pages/api.md
- perf/bench1.txt
- perf/bench2.txt
- perf/bench8.txt
- src/SizedArray.jl
- src/convert.jl
- src/lu.jl
- src/matrix_multiply_add.jl
- src/svd.jl
- test/SDiagonal.jl
Corrects many typos that I've found in the repository.
> Fix various typos

- Project.toml
- src/SArray.jl
- test/SVector.jl
> Fix missing tuple wrapper in sacollect

- test/initializers.jl
> Fix test failures with Julia nightly

- Project.toml
- src/SArray.jl
As per https://github.com/JuliaArrays/StaticArraysCore.jl/pull/21
> help Julia with type inference by providing `ntuple` with `Val`

- Project.toml
- src/broadcast.jl
- test/broadcast.jl
> Don't `@inbounds` function evaluation in broadcasting

- .github/workflows/Invalidations.yml
See https://github.com/JuliaArrays/StaticArrays.jl/pull/1087#discussion_r1675964364
> Fix comparison of invalidation counts

- src/eigen.jl
This matches the behavior for normal arrays
> Force convert diagonal to real in eigen(::Hermitian)

- Project.toml
To tag a new release with the recent PR.
> Bump version to 1.9.14
