JuliaArrays/StaticArrays.jl

src/arraymath.jl
src/matrix_multiply.jl
test/matrix_multiply.jl

I was using this in image processing and multiplying a matrix of `Float32` times a vector of `RGB{Float32}`.
The only risk here is that `zero(T)` might fail. I'm not sure what else to do, though.

Improve inference of eltype in matrix multiplication

---

src/arraymath.jl
test/arraymath.jl

For some reason, there's special rules using Base.promote_op to infer
the correct type for operations involving Number and arrays of other
types.  This means we need to overload promote_op or we'll get an Array
of Any in these cases.
See https://github.com/SimonDanisch/FixedSizeArrays.jl/issues/156 for a similar issue.

Make Array-of-SArray `op` Number infer the right output Array type

---

src/indexing.jl

Looks like the bounds-checking code was copied from functions where `m` is a matrix. Here that parameter is `a`. :)

Fix copy-paste error in some getindexes

---

src/SVector.jl
test/SVector.jl

This is an alternative---more minimalist---version of #47. It's not quite as convenient for the user, but it has one big advantage: this approach prevents "mission creep" in needing to define more and more methods for `CartesianIndex`. On balance I slightly favor this approach, but it's a close thing.

Define conversion and promotion for CartesianIndex

---

README.md
src/Scalar.jl
src/StaticArrays.jl
src/abstractarray.jl
test/Scalar.jl
test/runtests.jl

Better than `Array{T,0}` and `Ref` as scalar containers since this is immutable. It's useful for controlling broadcasting. Here is an example:
```
julia> s = Scalar(SVector(1,2,3))
0-dimensional StaticArrays.Scalar{StaticArrays.SVector{3,Int64}}:
[1,2,3]
julia> v = [SVector(1,2,3), SVector(0,0,0), SVector(10,10,10)]
3-element Array{StaticArrays.SVector{3,Int64},1}:
[1,2,3]   
[0,0,0]   
[10,10,10]
julia> v .+ s
3-element Array{StaticArrays.SVector{3,Int64},1}:
[2,4,6]   
[1,2,3]   
[11,12,13]
```
See some relevant discussions at:
https://github.com/JuliaArrays/StaticArrays.jl/issues/45#issuecomment-252975952
https://github.com/JuliaLang/julia/issues/18379
https://github.com/JuliaLang/julia/pull/18766#issuecomment-253031994

Added a `Scalar` type for 0-dimensional array

---

src/core.jl

More properly deal with the many types of statically-sized arrays by not inheriting from `DenseArray`. We do loose some free functionality from `Base`, but most methods were not type-stable and need to be reimplemented anyway.
(also some other minor fiddling)
CC @c42f

Inherit from AbstractArray not DenseArray

---

src/StaticArrays.jl
src/det.jl
src/traits.jl

Adds a trait-based scheme for dispatch on the size of a statically-sized arrays. The `Size{(m,n,...)}` type represents the trait (and currently isn't constructed). It's abstract supertype `SizeOf` helps implement the "traitor" style of automated trait dispatch whereby a supertype is used to construct a trait.
One standout feature is that it allows me to relax the type signature of a size-dispatched method to `AbstractArray`. As an example, similar methods to these are now defined:
```julia
det(x::StaticMatrix) = det(SizeOf(x), x)
det(::Type{Size{(1,1)}}, x::AbstractMatrix) = x[1,1]
det(::Type{Size{(2,2)}}, x::AbstractMatrix) = x[1,1]*x[2,2] - x[1,2]*x[2,1]
```
Using BenchmarkTools we see a 6.5x speedup on the 2x2 case:
```
julia> using StaticArrays, BenchmarkTools
julia> mat = [1.0 2.0; …
```

`Size` traits

---

src/SizedArray.jl
src/StaticArrays.jl
src/abstractarray.jl
src/det.jl

Now allows `Array` to use the (faster) algorithms from StaticArrays.jl, if the user knows the dimensions at compile-time. A convenience constructor from calling a `Size` instance is provided, e.g.
```julia
julia> Size(2,2)(rand(2,2))
2×2 StaticArrays.SizedArray{(2,2),Float64,2}:
0.367002  0.592863
0.725256  0.151296
julia> det(ans)  # Uses a StaticArrays `det()` method
-0.3744516359087295
```

Add `SizedArray` wrapper for `Array`

---

src/SArray.jl
test/SArray.jl

This doesn't address the root cause, but works around the issue reported in #76.

Workaround for comprehensions built from svectors

---

src/StaticArrays.jl
src/mapreduce.jl
test/mapreduce.jl

- Implement `reduce{D}(op, a, ::Type{Val{D}})` that takes `Val{D}` indicating the direction of reduction.
- Implement `maximum{D}(a, ::Type{Val{D}})` and `minimum{D}(a, ::Type{Val{D}})` using `reduce{D}(op, a, ::Type{Val{D}})`.
- Implement `diff{D}(a, ::Type{Val{D}})` separately, because it cannot be implemented using `reduce{D}(op, a, ::Type{Val{D}})`.

Implement versions of maximum(), minimum(), diff() with Val{dim} as second argument

---

src/mapreduce.jl

Change `a ? b:c` to `a ? b : c` for better readability.

Minor cosmetic change

---

src/MArray.jl
src/MMatrix.jl
src/MVector.jl
src/SArray.jl
src/SMatrix.jl
src/SVector.jl

Emitting the inline meta inside a macro causes unsuspecting user
functions to become inline, leading to surprises in type stability.
@andyferris it's all those generated functions, they've made you :meta :inline trigger happy :-P

Bugfix: Avoid emitting Expr(:meta, :inline) in a macro (!)

---

.travis.yml
src/FieldVector.jl
src/FixedSizeArrays.jl
src/MArray.jl
src/MMatrix.jl
src/MVector.jl
src/SArray.jl
src/SMatrix.jl
src/SVector.jl
src/Scalar.jl
src/SizedArray.jl
src/StaticArrays.jl
src/abstractarray.jl
src/core.jl
src/util.jl
test/FieldVector.jl
test/fixed_size_arrays.jl
test/runtests.jl

Define `similar_type` per type to avoid hooking into type internals.
Restructure code a bit to avoid old world problems
Disable FixedSizeArrays since current approach is not feasible on Julia 0.6
This is a minimal fix for the package on Julia 0.6. The fix of 265 requires that all methods used in generated functions are defined before generated functions that use the methods. Consequently, I've restructured the code a bit such that some of the generated functions are defined later. I guess the way generated functions are used could makes it harder to support user defined functions since they are defined later than the generated functions but the tests for `FieldVector`s pass.

Update to work on Julia 0.6

---

README.md
src/FieldVector.jl
src/FixedSizeArrays.jl
src/MArray.jl
src/MMatrix.jl
src/MVector.jl
src/SArray.jl
src/SMatrix.jl
src/SVector.jl
src/Scalar.jl
src/SizedArray.jl
src/StaticArrays.jl
src/abstractarray.jl
src/arraymath.jl
src/core.jl
src/deque.jl
src/indexing.jl
src/linalg.jl
src/mapreduce.jl
src/matrix_multiply.jl
src/traits.jl
test/FieldVector.jl
test/abstractarray.jl
test/arraymath.jl
test/deque.jl
test/fixed_size_arrays.jl
test/linalg.jl
test/mapreduce.jl
test/matrix_multiply.jl

* Now we use `Size` more consistently and rely less on `@pure` implementations of `similar_type`.
* `similar` and `similar_type` both use `Size` not integers to discuss size
* `similar` and `similar_type` are now streamlined. Users only need to
override one definition, just like in Base.
* Associated documentation and test changes.

Rewrite all `@pure` functions

---

REQUIRE
appveyor.yml
src/FieldVector.jl
src/ImmutableArrays.jl
src/MArray.jl
src/MMatrix.jl
src/MVector.jl
src/SArray.jl
src/SMatrix.jl
src/SVector.jl
src/SizedArray.jl
src/StaticArrays.jl
src/abstractarray.jl
src/core.jl
src/matrix_multiply.jl
src/traits.jl
src/util.jl
test/abstractarray.jl
test/fixed_size_arrays.jl
test/runtests.jl

The new syntax for inner constructors doesn't parse on 0.5 so it will be ugly and more demanding to support on both versions. Furthermore, 0.6 will be out soon and nobody will care about 0.5. If they care anyway and we add features then we can backport those features to a 0.5 branch.

Use new inner constructor and type declaration syntax

---

src/broadcast.jl
src/mapreduce.jl

to avoid defining methods that don't make much sense like `mapreduce(f, op)`

modify varargs signatures to ensure at least one input

---

src/indexing.jl
test/indexing.jl

See #128.
I forgot to provide methods for linear indexing of non-scalar values like `matrix[:]` and `matrix[SVector(1,2,3)]`. This PR implements the missing methods.

Fix linear indexing

---

src/broadcast.jl

A recent PR made some other signatures not define the zero-input version of certain functions where they are not defined in Base. In this case, this seems somewhat unnecessary since there is already a `broadcast(f, ::Number...)` method in `Base`.
The alternative is to define `broadcast(f, ::Number)` method here to remove the ambiguity. This seems like type piracy...
See #132.

Make `broadcast` signature compatible with `Base`.

---

src/mapreduce.jl
src/traits.jl
test/linalg.jl
test/mapreduce.jl

This allows StaticArray/AbstractArray linear algebra + and - to return a static array.
Here the versions of `map()` only support StaticArray up to the second argument for mixtures of StaticArray and AbstractArray.  Dealing with the ambiguities for longer argument lists becomes increasingly annoying!
I also upgraded `same_size` to work with mixtures of static and abstract arrays, and put it into traits.jl as it seemed to fit there.
Still todo is to fix matrix*vec to be size inferrable with a smatrix input, but that could be a separate PR.

Make map() take mixtures of StaticArray and AbstractArray

---

src/matrix_multiply.jl
test/matrix_multiply.jl

This was present prior to the big 0.6 rewrite, and should be reinstated for convenience as the output can be size inferred.  This PR is a bit copy-and-paste-ish, though not a lot worse than what's there already, I guess.
This is an associated fix for #131

Reinstate StaticMatrix * AbstractVector -> StaticVector

---

src/indexing.jl
test/indexing.jl

Wokraround for JuliaLang/julia#21244.
I briefly tried adding a test case similar to the one from JuliaLang/julia#21244, but it seems to need the `struct Foo` which cannot be defined inside a `@testset`. Is it worth to define such a type globally in `runtests.jl`?

Workaround for type inference problem in `index_sizes`

---

src/matrix_multiply.jl
test/matrix_multiply.jl

Fixes https://github.com/FugroRoames/CoordinateTransformations.jl/issues/28.

Enforce usage of `similar_type` for matrix multiplication

---

README.md
src/FieldVector.jl
src/MArray.jl
src/MMatrix.jl
src/MVector.jl
src/SArray.jl
src/SMatrix.jl
src/SUnitRange.jl
src/SVector.jl
src/Scalar.jl
src/SizedArray.jl
src/StaticArrays.jl
src/abstractarray.jl
src/arraymath.jl
src/deque.jl
src/det.jl
src/indexing.jl
src/linalg.jl
src/mapreduce.jl
src/matrix_multiply.jl
src/solve.jl
src/traits.jl
test/FieldVector.jl
test/SUnitRange.jl
test/abstractarray.jl
test/custom_types.jl
test/runtests.jl
test/solve.jl

This is a continuation of #127 whereby we add a `Tuple{...}` size descriptor to the abstract `StaticArray` type.
I'm previewing this WIP to get feedback on the interface, such as whether we want `StaticArray{Size, T, N}`, or have the dimensions after `T`, or after `N`. Any comments appreciated, otherwise I'll carry on.

WIP Add size to abstract StaticArray type

---

README.md
src/StaticArrays.jl

This isn't a complete review of the docs, but I did give the README a read through.

Various doc updates as fallout from merging #127, #134.

---

src/abstractarray.jl

@Keno this is an updated version of your PR.
Resolves #137

Define `size` more explicitly, helping the compiler

---

src/indexing.jl
test/indexing.jl

Was accidentally overiden for single argument case, assuming a kind of
a non-scalar linear indexing.
Fixes #141

Restore fancy APL indexing

---

src/SizedArray.jl
test/SizedArray.jl
test/runtests.jl

I ran into this problem working on a project that uses StaticArrays. I don't know the StaticArrays
codebase at all, so this may be wrong, but it has solved the problem for me.
Before this patch:
```
julia> StaticArrays.SizedMatrix{Tuple{2,2}, Float64}()
ERROR: MethodError: Cannot `convert` an object of type Type{Tuple{2,2}} to an object of type Array{Float64,2}
This may have arisen from a call to the constructor Array{Float64,2}(...),
since type constructors fall back to convert methods.
Stacktrace:
[1] Type at /home/steve/.julia/v0.6/StaticArrays/src/SizedArray.jl:23 [inlined]
[2] StaticArrays.SizedArray{Tuple{2,2},Float64,2,M} where M() at /home/steve/.julia/v0.6/StaticArrays/src/SizedArray.jl:31
```
After this patch:
```
julia> StaticArrays.SizedMatrix{Tuple{2,2}, Float64}()
2×2 …
```

Fix default constructor for SizedArray

---

src/StaticArrays.jl
src/io.jl
test/io.jl
test/runtests.jl

Unfortunately these allocate, but there doesn't seem to be a way to
avoid this yet, until the compiler can allocate Base.RefValue on the
stack (even Base.read(io, Float64) allocates!)
I'll also have to make a parallel version of this for the 0.5 branch, unfortunately.

Implement read() write() and read!() for static arrays

---

src/linalg.jl
src/matrix_multiply.jl
test/linalg.jl
test/matrix_multiply.jl

Promote hcat vcat

---

src/FieldVector.jl

I'm not 100% sure this change is correct, but without it I see a method ambiguity error when trying to pass a `FieldVector` through `ccall`:
```
MethodError: Base.unsafe_convert(::Type{Ptr{LibHealpix.UnitVector}}, ::Base.RefValue{LibHealpix.UnitVector}) is ambiguous. Candidates:
unsafe_convert(::Type{Ptr{T}}, m::Base.RefValue{FV}) where {T, FV<:StaticArrays.FieldVector} in StaticArrays at /home/michael/.julia/v0.6/StaticArrays/src/FieldVector.jl:27
unsafe_convert(P::Type{Ptr{T}}, b::Base.RefValue{T}) where T in Base at refpointer.jl:56
```
where `LibHealpix.UnitVector <: FieldVector{3, Float64}`.

fix a method ambiguity error in unsafe_convert for FieldVectors

---

src/StaticArrays.jl
src/expm.jl
test/expm.jl
test/runtests.jl

I have only tried this in julia v0.5, which is why the PR is to the julia-0.5 branch. You could probably cherry pick it to master.
Note: On my computer this gives a speedup of over 300x
```julia
a = randn(SMatrix{2,2})
b = Array(a)
@benchmark expm(a)
@benchmark expm(b)
```

Add matrix exponential for 1x1 and 2x2, and fallback to Base (fixes #159)

---

src/MMatrix.jl
src/MVector.jl
src/SMatrix.jl
src/SVector.jl
src/Scalar.jl

Remove most Tuple conversion functions now that most types have become
subtypes of SArray / MArray.  The scalar version of these was buggy.
Should fix test failures in #175 and #161

Bugfix for Tuple(::Scalar)

---

REQUIRE

`abstract type` won't work on early 0.6.0-dev versions,
so better to stick with the julia-0.5-compatible versions of the package there

use 0.6.0-pre for minimum julia version in REQUIRE

---

src/broadcast.jl
test/arraymath.jl
test/broadcast.jl

Fix broadcast issue

---

src/solve.jl
test/solve.jl

Firstly, thanks for great package.
I needed to solve some triangular systems with static arrays and thought that you might find a pull request useful. Below are a couple of quick benchmarks. I'm not sure how you decide on your huristics so I haven't added any fall backs to the methods in Base yet.
```julia
A = randn(n, n) |> t -> chol(t't);
b = A*ones(n, 2);
SA = UpperTriangular(SMatrix{n, n}(A.data));
Sb = SMatrix{n, 2}(b);
```
For `n=3` the results for `@benchmark A \ b` are:
BenchmarkTools.Trial: 
memory estimate:  144 bytes
allocs estimate:  2
minimum time:     261.064 ns (0.00% GC)
median time:      270.437 ns (0.00% GC)
mean time:        284.320 ns (3.11% GC)
maximum time:     4.887 μs (89.11% GC)
samples:          10000
evals/sample:     343
And the results for `@benchmark SA \ Sb` …

Add simple forward and backward substitution to solve triangular systems

---

src/StaticArrays.jl
src/eigen.jl
src/mapreduce.jl
test/eigen.jl

`sumabs` and `sumabs2` are deprecated. But since they are still exported from `base/deprecated.jl` nothing complained. The deprecation from base will work for this (if anyone relied on it):
```julia
julia> v = randn(SVector{3,Float64});
julia> sumabs2(v)
WARNING: sumabs2(x) is deprecated, use sum(abs2, x) instead.
Stacktrace:
[1] depwarn(::String, ::Symbol) at ./deprecated.jl:64
[2] sumabs2(::SVector{3,Float64}) at ./deprecated.jl:51
[3] eval(::Module, ::Any) at ./boot.jl:235
[4] eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:66
[5] macro expansion at ./REPL.jl:97 [inlined]
[6] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
while loading no file, in expression starting on line 0
1.3744999105444324
```

remove sumabs and sumabs2

---

src/matrix_multiply.jl
test/matrix_multiply.jl

This makes matrix multiply infer the type of the result in the same way Base does. One immediate result is that block matrix multiplication now works, 
```julia
julia> m=[1 2; 3 4]
2×2 Array{Int64,2}:
1  2
3  4
julia> bm = @SMatrix [m m; m m]
2×2 StaticArrays.SArray{Tuple{2,2},Array{Int64,2},2,4}:
[1 2; 3 4]  [1 2; 3 4]
[1 2; 3 4]  [1 2; 3 4]
julia> bm * bm
2×2 StaticArrays.SArray{Tuple{2,2},Array{Int64,2},2,4}:
[14 20; 30 44]  [14 20; 30 44]
[14 20; 30 44]  [14 20; 30 44]
```
whereas before it was 
```julia
julia> bm * bm
ERROR: MethodError: no method matching zero(::Type{Array{Int64,2}})
Closest candidates are:
zero(::Type{Base.LibGit2.GitHash}) at libgit2/oid.jl:106
zero(::Type{Base.Pkg.Resolve.VersionWeights.VWPreBuildItem}) at pkg/resolve/versionweight.jl:82 …
```

make matprod inference consistent with Base

---

src/StaticArrays.jl
src/linalg.jl
test/linalg.jl

This PR implements a type-stable `diag` function for `SMatrix`.  Specifically, for `A::SMatrix`, 
- `diag(A)` returns the main diagonal of `A` as `SVector`.
- `diag(A, Val{k})` returns the `k`th diagonal of `A` as `SVector`.  (The contents of the result are the same as `diag(A, k)`, but the resulting type is `SVector` instead of `Vector`.)
The PR also adds simple tests on the newly implemented `diag`.

Implement diag() with Val as second argument

---

src/indexing.jl

To workaround JuliaLang/julia#22458 convert a `Size((s1, ..., sN))` into
a `(Size(s1), ..., Size(sN))` and iterate over this tuple along with the
`inds` tuple (by simply calling `map`).

Make `index_sizes` inferable on Julia 0.7

---

src/broadcast.jl
test/Scalar.jl
test/broadcast.jl

Generalize broadcast to follow the julia-0.6 rules for defining which
values are scalars.
I haven't bothered to implement `promote_containertype` for a combination of `Tuple` and `StaticArray` yet because it's a bit more work and it seems a little questionable that people would even use this combination rather than just using `StaticVector`.
Fixes #239

Integrate StaticArrays with julia 0.6 broadcast

---

src/convert.jl

Benchmark code:
```julia
using StaticArrays, BenchmarkTools
@benchmark convert(SMatrix{3, 3, Float64, 9}, x) setup = (x = rand(3, 3))
```
With `julia -O3 --check-bounds=no`, minimum benchmark time goes from  5.456 ns to 2.302 ns.

Add @boundscheck annotation to bounds check in convert method

---

src/broadcast.jl
test/broadcast.jl

I'm not sure I have time for a full fix right now, so here's a lazy one which at least addresses the bug by falling back to the Base implementation for mixtures of static and non-static arrays.
Fixes #249

Fix broadcast! with non-static arrays

---

src/linalg.jl
test/linalg.jl

This PR implements `diagm(::SVector, ::Type{Val{k}})`, which type-stably creates a matrix with a specified `k`th super-or sub-diagonal.  Previously there was only `diagm(::SVector)` without the second argument.

Support Val{k} as second argument in diagm

---

REQUIRE

CI no longer tests the pre-releases, so it should require v0.6 instead.

Remove pre from minimum version

---

src/StaticArrays.jl
src/mapreduce.jl
test/mapreduce.jl

This PR adds more functions implemented with `[map]reduce` and `[map]reducedim` to `src/mapreduce.jl`:
-  `iszero`
- directional versions of `sum`, `prod`, `all`, `any`
- mapped version of `prod`, `count`, `all`, `any`, `minimum`, `maximum`
Note that `Base` already has these functions.
Additionally, this PR corrects the following typos:
- `reducedim(op, a::StaticArray, ::Val{D})` to `reducedim(op, a::StaticArray, ::Type{Val{D}})`
- `reducedim(op, a::StaticArray, ::Val{D}, v0)` to `reducedim(op, a::StaticArray, ::Type{Val{D}}, v0)`

Add more functions implemented with [map]reduce and [map]reducedim

---

src/broadcast.jl
src/mapreduce.jl
test/broadcast.jl

This PR fixes several issues raised for `broadcast` on `SArray`.  Specifically, 
- it broadcasts properly between `SArray` and `RowVec{<:Any,SVector}` to generate an `Sarray` (fixing #197, #200, #242), and
- it also produces a result consistent with `Base`'s for zero-length `SArary` (fixing #199).
- Additionally, it replaces `Base.promote_op` with `Core.Inference.returnt_type`, because the former infers a wrong return type of an operation when the input arguments of the operation are abstract (see https://discourse.julialang.org/t/alternatives-to-base-promote-op-op-type-for-op-type/5289/6).

Fix several broadcast issues (fixes #197, #199, #200, #242)

---

src/SDiagonal.jl
src/cholesky.jl
test/SDiagonal.jl
test/chol.jl

The second part is done by hooking into `Base.LinAlg._chol!`, which is imho the right way to do it but makes it necessary to keep track on base in this regard.

Specialise chol for SDiagonal and support static block matrices

---

src/arraymath.jl

The elements of instances of static arrays should be used as the set of items to draw from, as done in `Base`. Fixes #277.

Remove incorrect `rand` methods

---

src/mapreduce.jl

This works around a redefinition of `map` for all `AbstractArray` that occurs on v0.7 but not v0.6.
The newly-missed optimization opportunities are probably pretty rare in practice.

Fix `map` for Julia v0.7

---

src/det.jl

Minimalist version of #268. (Sorry Chris - we can do some size traits separately if we want, but may as well fix this quickly-er)
Fixes #267.

Minimalist logdet performance fix for large matrices

---

src/convert.jl

Use `@noinline` trick (see e.g. https://github.com/JuliaLang/julia/pull/23088#issuecomment-320279238) to speed up `convert(::Type{SA}, a::AbstractArray)` when bounds checks are turned on.
Benchmark:
```julia
using StaticArrays, BenchmarkTools
@benchmark SMatrix{4, 4}(a) setup = a = rand(4, 4)
```
On master:
```
BenchmarkTools.Trial: 
memory estimate:  0 bytes
allocs estimate:  0
--------------
minimum time:     14.114 ns (0.00% GC)
median time:      14.392 ns (0.00% GC)
mean time:        14.547 ns (0.00% GC)
maximum time:     43.770 ns (0.00% GC)
--------------
samples:          10000
evals/sample:     998
```
On this branch:
```
BenchmarkTools.Trial: 
memory estimate:  0 bytes
allocs estimate:  0
--------------
minimum time:     11.982 ns (0.00% GC)
median time:      12.057 ns (0.00% GC) …
```

Speed up conversion to StaticArray

---

src/det.jl
src/inv.jl
src/linalg.jl
test/det.jl
test/inv.jl
test/linalg.jl

Fix #310. I only added a tests for 3x3 which captures the mistake, but in general there is some serious undertesting of complex linear algebra.

Fix 3x3 det and inv for complex entries

---

src/cholesky.jl
src/mapreduce.jl
src/triangular.jl

Having eltype computations involving `one` and `zero` in the generator
code can introduce world age errors for user types which override these
functions after StaticArrays is included.  Instead, move these
computations into the bodies of the functions, and rely on inference to
optimize it away.
Fixes #316.
I'm not quite sure how to test this.  Could make a custom numeric type which overloads `one`, and test `diff` gets executed correctly, but arguably this kind of test with the custom type should be added for all code with generators.  Which is pretty intrusive and a fair amount of work.

Move eltype computations into generated function bodies

---

src/matrix_multiply.jl
test/matrix_multiply.jl

The size handling here was inconsistent in various places.  Fixes #323

Fix sizes in non-square medium sized matrix multiply

---

src/broadcast.jl
test/mapreduce.jl

Addresses the same problem as #330 but in a more minimal way.  Fixes #329 .
julia-0.6 doesn't seem to do constant propagation of `Type`s in quite
the way which would be required to get good efficiency for broadcasting
`round`.
Insert a minimal workaround for this particularly common case.

Workaround inference problem in round.(Int,v)

---

src/MArray.jl
src/SArray.jl
src/convert.jl
src/traits.jl
test/MArray.jl
test/MVector.jl
test/SArray.jl
test/core.jl

I'm not sure whether I've missed anything here, but calling `Tuple` seems like the simplest way to achieve a copying constructor.
Fixes #335 
The second commit here is a quick fix for some broken constructors I found when creating a test case for this.

Ensure static array constructors create copies

---

src/FixedSizeArrays.jl

I could have sworn that I already fixed this.
I'm not sure why this only turns up in a couple of cases - I can't even construct a test case for this.
But for some Arrays, mapreduce isn't able to correctly take the first element of the array as the reduce variable.
I remember debugging this already and it lead me to quite a bit of dark magic in the code of mapreduce.

fix extrema

---

src/FieldVector.jl
test/FieldVector.jl

don't allow FieldVector to be constructed from tuple of the wrong size

---

src/qr.jl
test/qr.jl

Fixes bug similar to [#24589](https://github.com/JuliaLang/julia/issues/24589) in Julia like in corresponding [PR](https://github.com/JuliaLang/julia/pull/24602). This fixes type stability and type promotion for `Rational{}` and so on.

Fix qr() type promotion

---

REQUIRE
src/SizedArray.jl
src/broadcast.jl
src/mapreduce.jl
test/Scalar.jl
test/runtests.jl

Fix Array{T}(uninitialized,...) deprecations

---

src/matrix_multiply.jl

The first commit fixes deprecations in `ccall` to BLAS `gemm`. Without it, I'm getting a segfault---might be some problem with the deprecations in Julia?
The second commit imports `LinearAlgebra.mul!` so that the definitions extend it instead of defining a new function.

Fixes for mul! on Julia 0.7

---

src/lu.jl
test/lu.jl

This is based on `generic_lufact!` from base, but using recursion instead of a `for` loop. It took me a few iterations of refinement, but the resulting code is satisfyingly clean. (Suggestions for a non-`@generated` alternative to `tailindices` welcome!)
For square matrices, it beats `lu(::Matrix)` up to a size of about 18×18. For sizes 2×2, 3×3, and 4×4, it provides a speedup of about 30, 15, and 9, respectively. At 25×25, it is slower by about a factor of two. (That's on Julia 0.6. Allocation of the input `Matrix` for `lu(::Matrix)` was not included in the benchmark, so comparison to the current implementation should be even a bit more favorable.)
Downside is significant compilation time. The recursion is completely inlined, so the functions can get really huge:
```julia
julia> m=20; …
```

Non-allocating LU decomposition

---

src/deque.jl

There is already a `setindex` function in `Base`, we should overload it.
It would allow to remove [this hack](https://github.com/jw3126/Setfield.jl/blob/41afdcf7e63d2f46a173661387049a31df730f4c/src/Setfield.jl).

overload Base.setindex

---

test/indexing.jl

Creating an empty `SArray` without specifying the element type leads to an element type of `Union{}` on Julia 0.6, but fails on Julia 0.7. Hence, the tests now explicitly define their element type.
Alternatively (hence RFC), we could define constructors for the empty case that default to an element type of `Union{}` to keep the 0.6 behavior on 0.7. Not sure how useful/desirable that is, but it would allow e.g. `SVector(x...)` to work even if `x` happens to be empty.

RFC: Fix "Indexing empty arrays" tests for Julia 0.7

---

src/MArray.jl
src/SArray.jl
src/SizedArray.jl
test/MArray.jl
test/SArray.jl
test/SizedArray.jl

An `SArray` can never alias anything, so it is safe to return an empty tuple here and prevent the aliasing detection machinery from doing unnecessary work.

Add `Base.dataids(::SArray)`

---

src/eigen.jl
test/eigen.jl

The handling of degenerate cases for 2x2 matrices was making the return type unstable. 
The method also claimed to be able to solve 3x3 Hermitian but didn't, so I restricted its type signature to real problems, so that it falls back on Arrays in that case. It's probably not too hard to extend the current method to complex problems, though.
edit: while I'm at it, fix for https://github.com/JuliaArrays/StaticArrays.jl/issues/364

Complex hermitian fixes

---

src/StaticArrays.jl

This was necessary for my code to work on julia master, since `eye` has been moved to `LinearAlgebra`.
Of course, it leaves me wondering whether any other imports have been missed.

Import `eye` from `LinearAlgebra` on julia 0.7

---

src/abstractarray.jl
src/broadcast.jl
src/deque.jl
src/linalg.jl
src/matrix_multiply.jl
src/traits.jl
src/triangular.jl

Mostly mechanical changes.
I did some very basic benchmarking of `sub2ind(s, i, j)` vs. `LinearIndices(s)[i,j]` and it looks like the latter on 0.7 is indeed equal to the former on 0.6 performance-wise, but `Compat.LinearIndices` (on 0.6) seems to be a tiny bit slower. Fortunately, these are almost only used in `@generated` function generators where performance is less of a concern. The only exception is `setindex` where I have introduced a `VERSION` dependency to be on the safe (performance) side.

Use `LinearIndices` instead of `sub2ind`

---

src/broadcast.jl
test/broadcast.jl

Fixes infinite recursion with generic broadcast code.

Fix #382: stack overflow from `SVector(1,1)' .+ [1, 1]`

---

src/broadcast.jl
test/broadcast.jl

This
```
julia> 3 * SVector(1, 2)
2-element Array{Int64,1}:
3
6
```
should return an `SVector`.  This wrong result is the consequence of a missing a `BroadcastStyle` declaration for broadcasting over an `StaticArray` and a scalar. This PR adds this missing rule, which fixes also other bugs such as e.g. `SMatrix{2}(1,2,3,4) * 3I` returning a `Matrix` instead of an `SMatrix`.

add missing BroadcastStyle for scalars

---

src/linalg.jl
src/triangular.jl
test/triangular.jl

Ensure that all tested multiplications involving one `AbstractTriangular{<:Any,<:StaticMatrix}` return an `SArray` (wrapped as necessary for row vectors) and allow non-zero imaginary part in tests, both on Julia 0.6 and 0.7.
For the test to pass on 0.7, https://github.com/JuliaLang/julia/pull/26349 is needed (otherwise computation of the `Array`-based reference results fails). Further, for `Pkg.test` to even reach the relevant testsets, #377 is required. But with those, things are looking good locally.

Improve/fix multiplication involving one AbstractTriangular{<:Any,<:StaticMatrix}

---

src/broadcast.jl
src/traits.jl
test/broadcast.jl
test/core.jl

Fix #385.
* extract `broadcast_size` function out of `broadcast_sizes`, which returns a single `Size` for a single ~~`AbstractArray`~~ argument
* extract `combine_sizes` function (similar to `Base.Broadcast.combine_indices`) out of `_broadcast`, to determine the appropriate destination `Size` from the right hand side arguments (`as...`)
~~* add `broadcast_dest_size` function, used by `broadcast!`, which selects the correct `Size` and checks that sizes match, given `broadcast_size(dest)` and `combine_sizes(broadcast_sizes(as...))`~~
~~On 0.6, `broadcast!` with a non-static LHS dispatches to generic `broadcast!` code in Base, both before this PR and after, meaning that some of this code won't get coverage on 0.6. I can change that if desired; it would probably result in a speedup as well.~~ …

Fix #385, broadcast! with non-static LHS broken on Julia master 

---

src/linalg.jl
test/SDiagonal.jl
test/eigen.jl
test/linalg.jl

Add `diagm(k1 => v1, k2 => v2, ...)` style interface, where the diagonals `k` are given as `Val` instances (not types!). Also use this syntax in the tests when calling `Base.diagm` to avoid deprecation warnings on Julia 0.7.
The old interface is left in place, but should be deprecated/deleted eventually.

diagm 0.7-style

---

src/deque.jl
test/deque.jl

This PR fixes setindex for multidimensional StaticArrays by using the `Length` trait instead of just pulling the first index from the `Size`. 
Fixes #401 
This doesn't resolve the still-existing issue that there's still no multi-dimensional bounds checking currently (I added two `@test_broken` tests to show the problem), so it's possible to call `setindex` using indices which are out of bounds for their individual axes, as long as the computed linear index is in range. AFAIK that doesn't create opportunity for segfaults or other bad behavior, but it's still something we should fix.

Fix `setindex` for multidimensional arrays

---

src/linalg.jl
src/util.jl
test/linalg.jl

Defines `kron` between two `StaticVector` types as well as between a `StaticVector` and a `StaticMatrix` type.  The definitions also include cases for transposed `StaticVector` types (i.e. a `StaticVector` wrapped by a `RowVector`type).
There are three broken tests which are due to the fact that taking the transpose of a `SizedArray` returns a `SMatrix`. I've made a comment in the relevant part of the test. Not sure of this behaviour of transpose is intentional or not?

Adds more Kronecker product specialisations

---

src/linalg.jl

The definition of  `kron(a::StaticVector, b::RowVector{<:Number,<:StaticArray})` is missing an explicit `promote_type` rule in its return statement. The code works fine without the explicit statement but I'm adding it for `symmetry` because all of the other `kron` definitions include the explicit `promote_type` rule.

Adds a missing explicit `promote_type` to the set of `kron` definitions

---

src/Scalar.jl
test/Scalar.jl

Fixes #414 (but see discussion point in that issue). This was also broken on 0.6, but this method just wasn't being called.

Resolve Scalar convert method ambiguity.

---

src/SDiagonal.jl
src/cholesky.jl
test/SDiagonal.jl
test/chol.jl

Note that the error handling is still a bit different as `_chol!` still throws an error instead of returning a non-zero `info`.

Make Cholesky factorization compatible with 0.7

---

src/arraymath.jl
test/arraymath.jl

On master + Julia 0.6.2, 
```julia
using StaticArrays
const TT = Complex{Float64} 
@allocated StaticArrays.arithmetic_closure(TT)
```
returns 224. This is a significant tax when working with `ForwardDiff.Dual`. It is fixed by this PR.

Specialize arithmetic_closure on type to eliminate allocation

---

test/indexing.jl

This set was introduced to test an inference issue (https://github.com/JuliaLang/julia/issues/21244) in an old version of Julia.
It currently fails on Julia master because of https://github.com/JuliaLang/julia/issues/27276.
In my opinion, it's currently not really testing anything valuable, and the Julia PR that fixed the issue has associated test cases that should cover this.

Remove "inferabilty of index_sizes helper" testset

---

src/StaticArrays.jl
src/broadcast.jl
src/linalg.jl
src/matrix_multiply.jl
src/triangular.jl
src/util.jl
test/SDiagonal.jl
test/broadcast.jl
test/linalg.jl
test/matrix_multiply.jl
test/svd.jl
test/triangular.jl

Fixes #416.
* get rid of iffy Adjoint definition for 0.6.
* define TransposeVector and AdjointVector.
* just use RowVector instead of Adjoint in 0.6-only code.
* simplify Size code a bit.
* use both adjoint and transpose in tests.
* convert tests to use transpose instead of `.'`.
Passes almost all tests on master now.

 Rework use of RowVector/ConjVector/Transpose/Adjoint.

---

src/linalg.jl
test/linalg.jl

Asking this question in the form a PR which can maybe be merged if the answer is yes, but shouldn't `transpose` and `ctranspose` be recursive like Base? 
For reference with Base (everything here is 0.6.2):
```julia
julia> [[[1 2; 3 4]] [[1 2; 3 4]]; [[1 2; 3 4]] [[1 2; 3 4]]]'
2×2 Array{Array{Int64,2},2}:
[1 3; 2 4]  [1 3; 2 4]
[1 3; 2 4]  [1 3; 2 4]
```
StaticArrays without this PR:
```julia
julia> (@SMatrix [[1 2; 3 4] [1 2; 3 4]; [1 2; 3 4] [1 2; 3 4]])'
2×2 StaticArrays.SArray{Tuple{2,2},Array{Int64,2},2,4}:
[1 2; 3 4]  [1 2; 3 4]
[1 2; 3 4]  [1 2; 3 4]                                                                                                        
```
and with it:
```julia
julia> (@SMatrix [[1 2; 3 4] [1 2; 3 4]; [1 2; 3 4] [1 2; 3 4]])'
2×2 …
```

make transpose and ctranspose recursive like Base

---

test/MArray.jl

I think again we are going through methods for `MVector` and `MMatrix` so I wrote a test which requires `MArray`.

PromoteType for MArray

---

src/arraymath.jl
test/arraymath.jl

Fixes #428. Pattern match `_fill` and `_rand` below.

Fix #428, zeros and ones shouldn't use _fill

---

src/SDiagonal.jl

Trivial fix for a v0.7 deprecation. The SDiagonal tests were broken without this because the deprecation itself was borked: https://github.com/JuliaLang/julia/pull/27505

handle deprecation of chol(::Number)

---

src/FixedSizeArrays.jl
src/arraymath.jl
test/REQUIRE
test/fixed_size_arrays.jl
test/runtests.jl

A couple things here: 
* A lot of the unary op tests in `test/fixed_size_arrays.jl` were silently failing because those functions have been moved to SpecialFunctions.jl, and the test itself is wrapped in a `try`
* I *maybe* fixed the random SArray generation? This is my first attempt at understanding the new way Random works. I didn't touch the `@inline rand(rng::AbstractRNG, range::AbstractArray, ::Type{SA}) where {SA <: StaticArray} = _rand(rng, range, Size(SA), SA)` method, which probably needs to be updated too.

fix FixedSizeArrays tests on v0.7

---

test/det.jl
test/inv.jl
test/lu.jl
test/solve.jl

This reduces total test time from about 16:30 to 6:20 on my machine. It also prints stuff more frequently for tests with a heavy compilation load, so that there's a smaller chance of having test timeouts.
The main win was not testing N = 50 for various tests due to https://github.com/JuliaArrays/StaticArrays.jl/issues/430#issuecomment-395977617. This approximately halved test time.
Fixes #430.

Reduce test time

---

src/expm.jl

Previously this code was casting large `Int64`s to `Int32` resulting in an `InexactError` (#438); the fix is to not cast to the input `eltype` `T` but instead to the result type `S = typeof((zero(T)*zero(T) + zero(T)*zero(T))/one(T))`. An alternative choice would have been `S = typeof(exp(zero(T)))` (used above in expm.jl), but I decided to stick with the `eltype` that would be returned by the algorithm at hand.

Cast expm Pade approximant coefficients to result eltype, fix #438

---

src/FixedSizeArrays.jl
src/SDiagonal.jl
src/SVector.jl
src/SizedArray.jl
src/traits.jl
test/core.jl
test/fixed_size_arrays.jl

Adding `S<:Tuple` ensured a method would be higher in the methodtable.

Activate helpful error message for undefined-Size conversions

---

src/StaticArrays.jl
test/mapreduce.jl

I wonder if we still need this specialized mean now that it requires an extra dependency. This dependency does not cost anything while Statistics comes with Julia, but might be something to consider removing in the future.

import mean from Statistics

---

src/linalg.jl
test/linalg.jl

Apparently this is a bit easier on the compiler.
(also just use `StaticVecOrMat` instead of `Union{StaticVector,StaticMatrix}`)

Fix #388, hcat allocations with Julia master

---

src/convert.jl
test/FieldVector.jl
test/MArray.jl
test/MMatrix.jl
test/MVector.jl
test/SArray.jl
test/SMatrix.jl
test/SVector.jl
test/Scalar.jl
test/core.jl

Fixes #446. The issue seems to be that `Tuple(::StaticArray)` does not fall back to `convert` as defined in the lines above this proposed change (see below) so one fix is to make that fallback explicit.
```julia
| | |_| | | | (_| |  |  Version 0.7.0-beta.125 (2018-07-02 20:55 UTC)
_/ |\__'_|_|_|\__'_|  |  Commit c5bf467361 (1 day old master)
|__/                   |  x86_64-linux-gnu
julia> using BenchmarkTools, StaticArrays
julia> struct Point3D <: FieldVector{3, Float64}
x::Float64
y::Float64
z::Float64
end
julia> p = rand(Point3D)
3-element Point3D:
0.6628326877139248
0.14765795872117993
0.48470441802594144
julia> @benchmark Point3D($p)
BenchmarkTools.Trial:
memory estimate:  224 bytes
allocs estimate:  6
--------------
minimum time:     342.486 ns (0.00% GC)
median time:      355.670 …
```

Add general Tuple(::StaticArray) constructor and remove related convert method

---

src/MArray.jl
src/MMatrix.jl
src/MVector.jl
src/indexing.jl

As remarked on [https://github.com/JuliaLang/julia/issues/29000](https://github.com/JuliaLang/julia/issues/29000), accessing an `MArray`, `MMatrix`, `MVector` sometimes pulls a stack copy. This patch avoids the stack copy, by using the pointer for `getindex` as well, not just for `setindex`.

fixed MMatrix boundschecks, faster getindex

---

docs/src/pages/api.md
src/abstractarray.jl

The old syntax seems to be deprecated now (https://github.com/JuliaLang/julia/blob/master/NEWS.md, first bullet point under "Language changes").

Doc update to reflect syntax change for parametric methods

---

src/SArray.jl
src/SMatrix.jl

Needed to work with GPUArrays. See: https://github.com/JuliaGPU/GPUArrays.jl/issues/157

Add @propagate_inbounds to getindex for SMatrix

---

.travis.yml
docs/make.jl

Deploy docs under 0.7

---

src/MArray.jl
src/MMatrix.jl
src/SDiagonal.jl
src/SMatrix.jl
src/SizedArray.jl
src/abstractarray.jl
src/broadcast.jl
src/linalg.jl
src/mapreduce.jl
test/SizedArray.jl
test/broadcast.jl
test/lu.jl

Solve various inference issues. Replaces #495 and #330.
Closes #493.
Note: the eltype of empty arrays may become `Union{}` in
`map`, `broadcast`, and `mapreduce(...; dims = Val{N})`.

Fix all the things

---

src/triangular.jl
test/triangular.jl

Adds specialized methods so that products of two `AbstractTriangular`s from `SMatrix`s results in another `SMatrix` (or a triangular, if both are upper/lower).
This partially fixes #508 because the `AbstractMatrix` converter for a `Cholesky` falls back on `U'U`, which now returns an `SMatrix` instead of a normal `Matrix`.

add specialized methods for Triangular * Triangular

---

src/StaticArrays.jl
src/flatten.jl
test/flatten.jl
test/runtests.jl

Before: 
```
julia> X = [@SVector rand(10) for i in 1:10000]
julia> @btime collect(Iterators.flatten(X))
1.402 ms (18 allocations: 2.00 MiB)
```
after 
```
julia> @btime collect(Iterators.flatten(Y))
365.198 μs (3 allocations: 781.34 KiB)
```

 Special case flatten of iterators of static arrays as done for tuples

---

src/FixedSizeArrays.jl
src/ImmutableArrays.jl

As briefly mentioned in #503 
At this stage, people should use the StaticArrays APIs directly. If there's anything useful left in StaticArrays.FixedSizeArrays we should fold it into the main API, or move it to other packages where it fits more neatly.
CC @andyferris @SimonDanisch 
[edit] Closes https://github.com/JuliaArrays/StaticArrays.jl/issues/459

Deprecate ImmutableArrays and FixedSizeArrays compatibility interfaces

---

src/FixedSizeArrays.jl
src/ImmutableArrays.jl

With the bug, `using StaticArrays.FixedSizeArrays` did not result in a
module name `FixedSizeArrays` in the current namespace, thus breaking
explicitly qualified name lookups like `FixedSizeArrays.Vec(1,2)`.
Provide a binding for this explicitly.
@fredrikekre — here's one possible fix. Thoughts?

Fix bug in module deprecation from 0.9.0 release

---

src/eigen.jl
test/eigen.jl

Fixes #523. I also reduced the amount of `@inbounds` by tearing it to the outside. I think it should apply everywhere in the following block.
Some questions:
* Is `T` equal to `eltype(A)`?
* Is there a noticeable difference between `TA(1)`, `TA(0)` and `one(TA)`, `zero(TA)`?
TODO: add tests for the diagonal 2x2 case.

(RFC) fix eigen in the diagonal 2x2-case

---

src/MArray.jl

#484 caused #529 (cc @chethega ) and these `GC.@preserve` fixes it.

Add GC.at-preserve for some pointer calls, fix #529.

---

src/SDiagonal.jl
test/SDiagonal.jl

Fixes #531. I've kept SDiagonal as a type alias for compatibility.

Use LinearAlgebra.Diagonal instead of defining SDiagonal type

---

src/SOneTo.jl
src/StaticArrays.jl
src/abstractarray.jl

This has been on the to-do list for 2 years! :tada: 
Now `axes(::StaticArray)` will return a tuple of "static unit ranges / slices". The `SOneTo` type lives under `AbstractUnitRange` so it can work properly with `Base`, and is therefore not a `StaticArray` subtype.
One interesting side-effect is what happens to `collect`:
```julia
julia> v = SVector(1,2,3)
3-element SArray{Tuple{3},Int64,1,3}:
1
2
3
julia> [x for x in v]
3-element SizedArray{Tuple{3},Int64,1,1}:
1
2
3
```
This matches the *OffsetArrays* package... basically if you want to mess with `axes` your behavior is automatically used by `collect`, and in particular for offsets (`Slice`s) you kind of need to rely on this to work out properly. I guess we should roll with this for now. If we can get generator/comprehension syntax …

Add `SOneTo` as `AbstractUnitRange` to represent `axes(::StaticArray)`

---

src/abstractarray.jl
test/abstractarray.jl
test/indexing.jl
test/matrix_multiply.jl

Make MArray stay mutable

---

src/convert.jl

Seems reasonable to use the "official" exception type here. We don't seem to have a specific test for this (it's probably a `@test_throws Exception ...` test); I can make it more specific if desired.

Return DimensionMismatch rather than ErrorException

---

src/SOneTo.jl
src/abstractarray.jl
src/broadcast.jl
test/broadcast.jl
test/core.jl

Fix inference on axes for broadcasting

---

src/SOneTo.jl
test/core.jl

Discovered in the context of
```julia
julia> a = SVector(SVector(1,2), SVector(3,4))
2-element SArray{Tuple{2},SArray{Tuple{2},Int64,1,2},1,2}:                                                                                                                                                                                                                     
[1, 2]                                                                                                                                                                                                                                                                        
[3, 4] …
```

Support construction/conversion of UnitRange->SOneTo

---

src/matrix_multiply.jl
test/matrix_multiply.jl

Adds dispatch rules for column vector times transpose(row vector)

---

src/linalg.jl
test/linalg.jl

For reference, Base does:
```
julia> using LinearAlgebra
julia> dot([[1,2], [3,4]], [[1,2], [3,4]])
30
julia> [[1,2], [3,4]]' * [[1,2], [3,4]]
30
```
whereas StaticArrays before this PR:
```
julia> dot(@SVector[[1,2],[3,4]], @SVector[[1,2],[3,4]])
ERROR: MethodError: no method matching *(::Array{Int64,1}, ::Array{Int64,1})
Stacktrace:
[1] macro expansion at /home/marius/.julia/packages/StaticArrays/3ENSR/src/linalg.jl:238 [inlined]
[2] _vecdot at /home/marius/.julia/packages/StaticArrays/3ENSR/src/linalg.jl:227 [inlined]
[3] dot(::SArray{Tuple{2},Array{Int64,1},1,2}, ::SArray{Tuple{2},Array{Int64,1},1,2}) at /home/marius/.julia/packages/StaticArrays/3ENSR/src/linalg.jl:225
[4] top-level scope at none:0
julia> @SVector[[1,2],[3,4]]' * @SVector[[1,2],[3,4]]
ERROR: MethodError: no method …
```

make dot recursive like Base

---

src/StaticArrays.jl
src/abstractarray.jl
src/convert.jl
src/linalg.jl
src/traits.jl
src/util.jl
test/core.jl
test/linalg.jl

Now that we have wrapper types in Base that can be used in conjunction
with StaticArrays, we should discern between actual `StaticArray`s and
non-`StaticArray` subtypes for which we still know a static `Size`. To
this effect, this PR adds the type aliases `StaticallySizedMatrix`,
`StaticallySizedVecOrMat`, and `StaticallySizedArray`, and uses them to
widen various type signatures.
Fixes #561.

Introduce StaticArrayLike

---

src/SOneTo.jl
src/abstractarray.jl
test/abstractarray.jl

This restructures the similar method table along the lines that I suggested in https://github.com/JuliaArrays/StaticArrays.jl/pull/568#discussion_r241561280. I also used a bit of internals magic to match how the Base `OneTo` operates -- this is a little fragile but I think it is a good way to replicate how `OneTo` works.

Alternate approach to fix #556

---

src/MMatrix.jl
src/SMatrix.jl
src/StaticArrays.jl
src/arraymath.jl
src/broadcast.jl
src/deque.jl
src/indexing.jl
src/mapreduce.jl
src/matrix_multiply.jl
src/triangular.jl
test/indexing.jl

Several aspects of indexing were not ideal:
- `getindex(a::StaticArray, inds::Int...)` violates the [AbstractArray interface](https://docs.julialang.org/en/latest/manual/interfaces/#man-interface-array-1)
- non-scalar static indexing of `AbstractArrays` only worked up to 4 dimensions
- there were a lot of `getindex` and `setindex!` ambiguities
The first commit here fixes all of these problems while also reducing `detect_ambiguities(Base, StaticArrays)` from 35 pairs to 9. Serious progress on #18 :fireworks: .
The second is boring but addresses https://github.com/JuliaLang/julia/issues/6383#issuecomment-448642771. A `sed` script to fix this is
```sh
sed -i "s/StaticArray{<:Any/StaticArray{<:Tuple/g" *.jl
```
if this ever creeps back in.

Clean up indexing and dispatch

---

src/SDiagonal.jl
src/lu.jl
test/solve.jl

Because of [this depot function](https://github.com/JuliaLang/julia/blob/eddcbd7585152c1e404ed0481ffe44c61d504e77/stdlib/LinearAlgebra/src/generic.jl#L891-L908) we need to handle a variety of different cases for `\`.
This doesn't work yet for a nominally-unrelated indexing reason: the `B[F.p, :]` fails. Out of time for tonight.

implement solve with mixed StaticArray/DynamicArray types

---

src/StaticArrays.jl
src/abstractarray.jl
src/convert.jl
test/abstractarray.jl
test/convert.jl
test/runtests.jl

Tuple creation is unnecessary for SizedArrays and causes massive slowdown for big arrays.

No tuple creation for SizedArrays

---

src/mapreduce.jl
test/mapreduce.jl

Fixes #593. Note that run-time behavior should be unaffected (in cases where inference is unaffected) as the `same_size` call is merely moved.

Improve inferability of resursive `map` on nested `StaticArray`s

---

src/abstractarray.jl
test/abstractarray.jl

This PR fixes
```julia
using StaticArrays
X = @SVector [1, 2.5, 3]
reshape(X, axes(X))
```
which fails currently and causes test failures in LabelledArrays (see https://travis-ci.com/JuliaDiffEq/LabelledArrays.jl/jobs/178867473).

Reshape with tuple of SOneTo

---

src/broadcast.jl
test/broadcast.jl

The problem can be replicated on master with `Array{Int, 0}(undef) .= Scalar(42)`. The fix just adds a quick check for a zero-dimensional case.

fix for zero-dimensional broadcast bug in generated function

---

src/svd.jl
test/svd.jl

A small update to the `svd` wrapper so that `full=true` is supported. Code occasionally uses this, for example `nullspace`... in fact this is the only place `full=true` occurs in `LinearAlgebra`.
XRef: https://discourse.julialang.org/t/why-julia-and-linear-algebra-module-are-incredibly-slow-compare-to-c-and-eigen/21304/6

Support for `svd(::StaticMatrix, full=true)`

---

src/indexing.jl
test/indexing.jl

The PR allows using static arras as index when using views, such as
~~~~julia
a = [10,20,30,40]
idx = SVector(2,4)
b = view(a, idx)
~~~~

Allow using static arrays as index for views

---

src/solve.jl

Concerning [this issue](https://github.com/JuliaArrays/StaticArrays.jl/issues/582#issue-398546390).
My proposal for increased performance of A/B if A is 2x2 or 3x3 and B is 2or3xn.
There is an [ongoing discussion](https://discourse.julialang.org/t/performance-of-matrix-division/19477?u=judober) about this.

Increase Performance of \ (and /) for small square matrix

---

src/Scalar.jl
src/indexing.jl
test/MArray.jl

Allow empty indexing of zero-dimensional MArrays

---

src/linalg.jl

Ref https://github.com/JuliaArrays/StaticArrays.jl/issues/512. Use `@simd` in `_vecdot` instead of manually unrolling and relying on the SLP vectorizer.
I noticed that the current implementation never uses 256-bit wide instructions (no `ymm` registers being used), while the `@simd` version does. Note that using `@simd` in conjunction with the statically known size of the matrix, the loop is fully unrolled up to a reasonable threshold even without using a generated function.
The naive benchmark; but I'm doubtful that this gives accurate results.
```julia
using StaticArrays
using LinearAlgebra
using BenchmarkTools
for n in [0 : 32; 100]
b = @benchmark dot(x, y) setup = begin
x = rand(SVector{$n, Float64})
y = rand(SVector{$n, Float64})
end
println(minimum(b.times))
end
```
Results:
`n` | …

Use `@simd` in `_vecdot`

---

src/solve.jl
test/solve.jl

Fix A\B where A is nonsquare

---

src/convert.jl
test/convert.jl

Fix constructor for SVector{0} from Array

---

.travis.yml
appveyor.yml
test/SHermitianCompact.jl

XRef: https://discourse.julialang.org/t/julia-v1-2-0-rc1-is-now-available/24788

Enable CI for julia version 1.2

---

README.md
docs/src/pages/quickstart.md

I have noticed, that some of the code examples in the `Quick start` section of the README don't work because they were designed for an older version of Julia. This PR modifies these examples to make them work with Julia v1.1.1.

Adopt examples in README to current Julia version

---

src/indexing.jl
src/svd.jl
test/abstractarray.jl
test/indexing.jl
test/svd.jl

#613 didn't have adequate test coverage for solving problems like `svd(A) \ v` when `A` is non-square. It worked for the "thin" decomposition, but `svd(A; full=Val(true)) \ v` failed.
While implementing this I noticed what appeared to be missing support for indexing StaticArrays with `SOneTo`. This led to a change in one test result (see bea22b412c1f1330823f060cebfdf7515ac48d2d), so this is worth thinking about carefully and is a breaking change.

Change SOneTo indexing and support \ for svd(M; full=true)

---

src/SizedArray.jl
src/util.jl

This small change speeds up `similar` for `SizedArray`.
Before:
```julia
julia> using BenchmarkTools
julia> a = SizedArray{Tuple{2,2}}([1.0 2.0; 3.0 4.0])
2×2 SizedArray{Tuple{2,2},Float64,2,2}:
1.0  2.0
3.0  4.0
julia> @benchmark similar($a)
BenchmarkTools.Trial: 
memory estimate:  128 bytes
allocs estimate:  2
--------------
minimum time:     177.235 ns (0.00% GC)
median time:      179.944 ns (0.00% GC)
mean time:        206.715 ns (8.87% GC)
maximum time:     90.985 μs (99.74% GC)
--------------
samples:          10000
evals/sample:     714
```
After:
```julia
julia> @benchmark similar($a)
BenchmarkTools.Trial: 
memory estimate:  128 bytes
allocs estimate:  2
--------------
minimum time:     40.421 ns (0.00% GC)
median time:      45.254 ns (0.00% GC)
mean …
```

Faster similar for SizedArray

---

src/deque.jl

Also tested the new docstrings locally
The main "critique" I could make is that putting `-> vec` may imply the original `vec` is returned rather than a modified one.  Suggestions welcome for making this more clear.

Add docstrings for push, pop, pushfirst, popfirst, insert, deleteat

---

src/mapreduce.jl
test/mapreduce.jl

This change makes `in` unroll the loop (compared to `Base.in`) and is
significantly faster.

add `in` method

---

src/indexing.jl
test/indexing.jl

This PR attempts to allow indexing operations of the form `indexee[indexer]` where both *indexer* and *indexee* may be multidimensional.
This was previously possible if *indexer* was one-dimensional (seems to have gone down the linear indexing branch of the code) or if *indexee* was one-dimensional, but *indexer* may be multidimensional (this goes to the multidimensional indexing path, and there's a test for it so this must have been intentional).
This sends all `getindex(::StaticArray, ::StaticArray)` down the linear indexing path (where they belong, IMO) by updating the methods of form `getindex(::StaticArray, ::StaticVector)` to accept arrays for the second argument. The other changes are natural consequences. Of course the same goes for setindex.
Note, I had to change the second …

Enable linear indexing with multidimensional index

---

src/indexing.jl

It was somewhat confusing to be told that I need to implement `getindex(::typeof(a), ::Int)` :-)

Fix default error message for getindex(::StaticArray, ::Int)

---

src/convert.jl
test/convert.jl

Fix eltype in empty static array construction

---

src/broadcast.jl
test/broadcast.jl

This simplifies code according to a tip left in a comment, by using `CartesianIndices` instead of generating indices manually. This also fixes #642 by not trying to increment an empty index.
I broke a long line there according to personal taste, if that's okay.

Simplify broadcast code generation

---

src/indexing.jl
test/indexing.jl

This allows `StaticIndexing` to appear at any position when making a view.
I'm not sure if it counts as type piracy or not but this shouldn't cause any issues.

[WIP] Nested views with static indexing

---

src/abstractarray.jl
test/abstractarray.jl

I need these methods for `HybridArrays` (views use them) and I think they belong here.

Base.strides methods for statically sized arrays

---

src/mapreduce.jl

I think this is the simplest possible solution for #540 . This essentially avoids passing around keyword arguments in some common use cases. I'll change other reduce-like functions if you think it's a good solution.

[WIP] faster reductions

---

README.md
docs/src/pages/quickstart.md
src/StaticArrays.jl
src/initializers.jl
test/initializers.jl

The discussion at #655 has stimulated what I feel is finally a reasonable solution to constructing small static arrays with precise eltype without too much typing:
```julia
SA_F64 = SA{Float64}
SA_F32 = SA{Float32}
v = SA_F64[1,2,3]  # A Float64 vector
v = SA_F32[1 2; 3 4]  # A 2x2 Float32 SMatrix
```
I don't love the underscore there, but `SAF64` looks very confusing.  Other than that, I think the naming here is consistent with the precedent set by `Base.ComplexF64`.
Better naming options welcome!
I believe this (along with #633) finally fixes #24 to the extent that we can have a solution to that.

SA type aliases for constructors with precise eltype

---

README.md
perf/README_benchmarks.jl

Since this affects the github front page of `StaticArrays.jl` these changes should probably be merged only once 0.7 is actually released.
Regarding badges - do we want to keep the 0.5 and 0.6 passing badges up indefinitely?

[WIP] README updates for 0.7

---

src/broadcast.jl
src/mapreduce.jl
test/broadcast.jl
test/linalg.jl
test/lu.jl
test/mapreduce.jl

This reverts to using `Core.Compiler.return_type` for map/broadcast, but
only in the very restricted case that the output container is completely
empty.
This is consistent with the way that return_type is used in Base for
collect and broadcast for empty collections only.
Fixes #528 using the strategy from https://github.com/JuliaArrays/StaticArrays.jl/issues/528#issuecomment-517110844

Avoid eltype degrading to `Union{}` for empty map/broadcast

---

src/initializers.jl

Surprisingly enough these result in methods which can be called but which don't inline, leading to performance problems.
```julia
julia> g(x) = SA[1 2; 3 x]
```
Before:
```
julia> @code_llvm g(1)
;  @ REPL[2]:1 within `g'
define void @julia_g_16110({ [4 x i64] }* noalias nocapture sret, i64) {
top:
%2 = alloca %jl_value_t addrspace(10)*, i32 7
%gcframe = alloca %jl_value_t addrspace(10)*, i32 3
%3 = bitcast %jl_value_t addrspace(10)** %gcframe to i8*
call void @llvm.memset.p0i8.i32(i8* %3, i8 0, i32 24, i32 0, i1 false)
%thread_ptr = call i8* asm "movq %fs:0, $0", "=r"()
%ptls_i8 = getelementptr i8, i8* %thread_ptr, i64 -15560
%ptls = bitcast i8* %ptls_i8 to %jl_value_t***
%4 = getelementptr %jl_value_t addrspace(10)*, %jl_value_t addrspace(10)** %gcframe, i32 0
%5 = bitcast %jl_value_t …
```

Remove some spurious `where T` from SA constructors

---

docs/src/pages/api.md

Some minor fixes to the docs.
- fix typos
- use em-dashes
- replaced `imbue` (probably a typo?) with `implement`
- replace `eig` with `eigen`

minor typo fixes and typesetting changes

---

README.md
docs/src/pages/api.md
docs/src/pages/quickstart.md
perf/benchmark2.jl
perf/benchmark3.jl
src/SizedArray.jl
src/abstractarray.jl
src/cholesky.jl
src/lyap.jl
src/sqrtm.jl
test/abstractarray.jl
test/convert.jl
test/flatten.jl

This feature makes it hard to find code which actually uses SizedArray (eg see https://github.com/JuliaArrays/StaticArrays.jl/pull/666#pullrequestreview-295372179), and it blesses `SizedArray` in an odd fashion by providing a special syntax for constructing it using the trait, which is completely different from the way that other `StaticArray` subtypes are constructed.
So I feel like it's an oddity which we should deprecate, perhaps.
If we do this, it's definitely breaking! But I also kind of suspect that a relatively small number of users actually use `SizedArray`. That's quite hard to assess though with a code search for the reasons mentioned...
One thing I'm not so sure about here is "what if you have `s::Size`, and you want to make a `SizedArray` which is that size"?  The natural …

RFC: Deprecate calling of Size to get SizedArray

---

src/SArray.jl

with promotion of user defined types. This is a minimal version of #670. I still think it would be beneficial to avoid generated functions when they aren't needed but it it's not urgent. In contrast this current issue is causing issues when using `StaticArrays` with `ForwardDiff` so it would be useful to get fixed immediately. I'd appreciate if you could make a bugfix release after merging this.

Avoid calling promote_tuple_eltype in generated function to fix issue

---

src/linalg.jl

The allcations were probably due to lack of proper inlining of the
`init=...` keyword, but we're not reducing empty vectors here (there's a
special case for that) so we shouldn't need `init` at all.
Should fix #678

Remove allocations with `norm(x, p)`

---

src/SizedArray.jl
test/SizedArray.jl
test/abstractarray.jl

I'm trying to port some improvements I've made in `HybridArrays` to `SizedArray` here. Full support for wrapping arbitrary `AbstractArray`s is a fairly large project and noticeable increase in complexity of `SizedArray` so I'm not sure if it's actually a good idea.
Anyway, here is a small change that:
1) makes sure that converting back to `Array` retains given static shape,
2) changes `Array(::SizedArray)` so that it makes a copy (since `Array(::Array)` also makes one).

Conversion of SizedArray to Array reshapes

---

src/initializers.jl

Looks like these were forgotten during refactoring

Remove some obsolete functions

---

src/initializers.jl
test/initializers.jl

`Union{}[]` does not work after I import `StaticArrays` (cb46c2dfb6e53b398a156ba7f6522f727ef26795) due to the new `SA[...]` constructor:
```julia
julia> Union{}[]
0-element Array{Union{},1}
julia> Union{}[]
ERROR: ArgumentError: Union{} does not have elements
Stacktrace:
[1] eltype(::Type{Union{}}) at ./array.jl:124
[2] similar_type(::Type{Union{}}, ::Size{(0,)}) at /home/takafumi/.julia/dev/StaticArrays/src/abstractarray.jl:66
[3] getindex(::Core.TypeofBottom) at /home/takafumi/.julia/dev/StaticArrays/src/initializers.jl:29
[4] top-level scope at REPL[3]:1
```
This PR fixes it by overloading type piracy by yet another type piracy.
(Though I'm not sure if this is technically a type piracy. If you can't overload anything that can accept `Type{Union{}}`, you can't …

Unpirate Union{}[]

---

test/initializers.jl
test/testutil.jl

Based on #685 (CC @tkf). I'll rebase once some solution to that issue is merged.
The implementation here is certainly hacky as it does a very simple minded inspection of the LLVM code as a string. But it should be much better to have some hacky tests for code quality rather than inspecting the code by eye!

A tool for testing whether codegen fully inlines a call tree.

---

src/abstractarray.jl
src/linalg.jl
test/abstractarray.jl
test/linalg.jl

This is where it belongs; it's array functionality rather than linear algebra.
Also return a throw expression for size mismatches rather than throwing
from function generators.

Move concatenation into abstractarray.jl

---

src/MArray.jl
src/MVector.jl
src/SArray.jl
src/SDiagonal.jl
src/SHermitianCompact.jl
src/SVector.jl
src/StaticArrays.jl
src/abstractarray.jl
src/det.jl
src/linalg.jl
src/qr.jl
src/util.jl
test/linalg.jl
test/testutil.jl

* Remove all reference to the deprecated name `eye` (replace internal
_eye with _scaler_matrix)
* Remove all the more-or-less duplicate definitions of one() and use
_scalar_matrix as the implementation.
* Fix StaticMatrixLike definition to properly include Hermitian and
Symmetric wrappers of static matrices.
* Import LinearAlgebra.checksquare() and use it directly.
Introduce `_construct_similar` to alleviate the difficulty of computing
eltype purely in the type domain with non-concrete UnionAlls.

Tidy one() implementation and UniformScaling constructors

---

src/eigen.jl
test/eigen.jl

Planned to help with #661 
For the (previously unhandled) non-hermitian branch of eigen, this PR falls back to `eigen(Array(A),...)`. To add in type stability, the type of the expected eigenvalues is added as a parameter that defaults to `real(eltype(A))` (which is consistent with the old implementation). Passing a complex type here allows the user to use `eigen(StaticMatrix)` even if they are not completely positive that the matrix will always be symmetric/hermitian.

Handle non-hermitian matrices in eigen

---

src/StaticArrays.jl
src/abstractarray.jl
src/lu.jl
src/traits.jl
src/triangular.jl
test/core.jl
test/lu.jl

Implement .P property for LU factorizations now that this can be inferred. In the process of doing this I did some trait cleanup, as `LU.U` is triangular.
* Add triangular matrix wrappers to StaticArrayLike
* Avoid defining `get()` for our traits as that collides with Base.get

Some trait + LU api cleanup

---

src/linalg.jl
test/linalg.jl

The eltype may change due to the recursive nature of adjoint and
transpose.
Fixes #708

Fix eltype for recurisve adjoint/transpose

---

src/broadcast.jl
test/broadcast.jl

A minor thing I ran into / fixed.

fix broadcasts with only adjoint/transpose SVectors

---

src/MArray.jl

`MArray{S,T,L}()` throws an error.

Fix MArray constructor docstring

---

src/abstractarray.jl
test/SizedArray.jl

I had an array, and I wanted to carry size information about it around in its type..
At first I thought, I can use a `SArray`, but then I remember my matrix might endup being something like 10^3 x 10^6 elements; and  creating a `SArray` would be really slow.
I looked in the docs and I spotted `SizedArray` and I am likle _Pefect_.
So I am happily using that.
Then at some point I needed to call `vec` on my `SizedArray`,
and after I did that, it had turned into a `SArray`.
Which I really did not want, reasons outlined above.
This fixed that.
The code was basically already there, I just uncommented and updated it.

make reshaping SizedArrays not turn them into SArrays

---

src/FieldArray.jl
test/FieldMatrix.jl
test/FieldVector.jl

This should free users from defining similar_type in many cases, though
they'll still need to do so when their type is parametric on the eltype.
(There's no general way for us to know how to reparameterize such
user-defined types.)
Fixes #729

Default implementation of similar_type for FieldArray

---

.gitignore
benchmark/Project.toml
benchmark/bench_qr.jl
benchmark/benchmarks.jl

See #737. Please comment on how we organize `benchmark/*` here.

Minimal benchmark setup

---

benchmark/Project.toml
benchmark/bench_matrix_ops.jl

This PR adds `benchmark/bench_matrix_ops.jl` which is a straight-forward port of `perf/benchmark_matrix_ops.jl`.

Port perf/benchmark_matrix_ops.jl to benchmark/*.jl

---

.github/workflows/benchmark.yml

See: https://github.com/JuliaArrays/StaticArrays.jl/pull/737#issuecomment-588475251
It's good to go (if this setup is desired) but I submit it as a draft to avoid accidentally merging this.

Suppress comments from BenchmarkCI

---

src/StaticArrays.jl
src/mapreduce.jl
test/mapreduce.jl

This PR includes some improvements discussed in https://github.com/JuliaArrays/StaticArrays.jl/pull/702#discussion_r379200418:
* Document how `_InitialValue` works and explain some idea behind it.
* Use `_InitialValue` instead of passing around `kw.data :: NamedTuple`.
* Use `_InitialValue` to collapse the foldl implementations with and without `init` into one.
* Add `mapfoldl` and `foldl` on static arrays:
1. Rename the reduce "kernels" `_mapreduce` to `_mapfoldl`.
2. Add `_mapreduce` back as an alias to `_mapfoldl`.
* This way, functions (e.g., `sum`) wrapping reduce can just call `_mapreduce`.
* I added this indirection to avoid another big diff in the future #751.  It may make sense to use the divide-and-conquer version for `_mapreduce` #748.
3. Define `Base.mapfoldl` and `Base.foldl` …

Define mapfoldl/foldl for static arrays

---

src/convert.jl
test/abstractarray.jl

Julia Base defines conversion to the abstract types `AbstractArray{T}` and `AbstractArray{T,N}` by invoking their (abstract) constructors. These fail with an error for static vectors (see #746).
This pull request defines the `AbstractArray{T}` and `AbstractArray{T,N}` constructors for static arrays in terms of `similar_type`. This enables the following:
```julia
julia> convert(AbstractVector{Float64}, SVector(1,2))
2-element SArray{Tuple{2},Float64,1,2} with indices SOneTo(2):
1.0
2.0
```
One use case is to generically change the element type of a vector, in the example above from `Int` to `Float64`.
I've added tests for SVector, SMatrix, MVector and MMatrix. Perhaps there are others?
Also, should the conversions perhaps be `@inline`?

support conversion to AbstractArray

---

src/linalg.jl
test/linalg.jl

Fix release-blocking bug #700 .
It turns out that Rotations.jl relies on `one(M)` calling the constructor of `M`, so transitioning to use of `simliar_type` in #690 broke `Rotations`. 
It's arguably a bug to call the constructor rather than calling `similar_type`, but let's avoid breaking compatibility for now.
I say it's arguably a bug because some sets of matrices defined by a type cannot represent the multiplicative identity, for example the set of skew-symmetric matrices. StaticArrays should likely assume that generic operations like `one()` must devolve to a matrix type which can represent
anything in GL(n,R).

Fix accidential API breakage in one()

---

src/StaticArrays.jl
src/det.jl
src/lu.jl
test/lu.jl

This makes the implementation of `lu` conform to the API of LinearAlgebra: check by default, optionally skip check.
Tests and methods that use `lu` are modified accordingly.

Add singularity checks for lu, method for issuccess.

---

src/MMatrix.jl
src/MVector.jl
src/SMatrix.jl
src/SUnitRange.jl
src/SVector.jl
src/Scalar.jl
test/SUnitRange.jl

Apparently these can be problematic for compiler-internal reasons, and I
think the printing has been improved such that the remaining cases of
these may not do anything useful. So let's just remove them.

Remove show(::IO, ::Type{StaticArrays.Blah}) overloads

---

src/StaticArrays.jl
src/det.jl
src/lu.jl
test/det.jl

1. define a `logabsdet` for `SMatrix`, fixes #489
2. define methods for `det`, `logdet`, `logabsdet` for LU (cf `LinearAlgebra`, which has these methods)
3. make `det`, `logdet`, `logabsdet` fall back to using the LU methods (to avoid code repetition)
4. include `lu.jl` first, since `det.jl` uses code from it
5. incidental consistency fixes

Define logabsdet(::SMatrix), det & friends for LU

---

.github/workflows/ci.yml

Quick fix (hopefully!) for CI failing on nightly.
Not exactly ideal though, see https://github.community/t5/GitHub-Actions/continue-on-error-allow-failure-UI-indication/td-p/37033
For reference, the failing job https://github.com/JuliaArrays/StaticArrays.jl/runs/625450952

Allow CI failures on Julia nightly builds

---

src/mapreduce.jl
test/mapreduce.jl

Fix reduction over empty array

---

src/traits.jl

`!=` should inline to `!(a == b)` anyways, but by defining those, there is a massive amount of method invalidation going on.
Compile times on master:
```
julia> @time using StaticArrays
[ Info: Precompiling StaticArrays [90137ffa-7385-5640-81b9-e52037218182]
5.000174 seconds (3.63 M allocations: 227.198 MiB, 0.06% gc time)
```
Compile times on this branch:
```
julia> @time using StaticArrays
[ Info: Precompiling StaticArrays [90137ffa-7385-5640-81b9-e52037218182]
4.748623 seconds (3.63 M allocations: 227.200 MiB, 0.05% gc time)
```

remove unnecessary definition of `!=`

---

src/SArray.jl

Before:
```
julia> detect_ambiguities(Base, LinearAlgebra, StaticArrays)
2-element Array{Tuple{Method,Method},1}:
(unsafe_convert(::Type{Ptr{T}}, a::Base.RefValue{SArray{S,T,D,L}}) where {S, T, D, L} in StaticArrays at /home/steve/.julia/dev/StaticArrays/src/SArray.jl:69, unsafe_convert(::Type{Ptr{Nothing}}, b::Base.RefValue{T}) where T in Base at refvalue.jl:30)
(convert(::Type{SA}, a::AbstractArray) where SA<:(SArray{Tuple{},T,0,1} where T) in StaticArrays at /home/steve/.julia/dev/StaticArrays/src/Scalar.jl:13, convert(::Type{SA}, sa::StaticArray) where SA<:StaticArray in StaticArrays at /home/steve/.julia/dev/StaticArrays/src/convert.jl:10)
```
After:
```
julia> detect_ambiguities(Base, LinearAlgebra, StaticArrays)
1-element Array{Tuple{Method,Method},1}:
(convert(::Type{SA}, …
```

remove ambiguity in unsafe_convert with RefValue

---

Project.toml
src/SArray.jl
src/SMatrix.jl
src/SVector.jl
test/MArray.jl
test/SArray.jl
test/SMatrix.jl
test/SVector.jl

Provide constructors from generators

---

src/SOneTo.jl
src/sort.jl
test/sort.jl

fixes #772 
- Is using `similar_type` for the index array a good idea?
- Do we want to keep stability semantics from Base or get more performance?

implement sortperm

---

src/mapreduce.jl
test/mapreduce.jl

The eltype of these can just be inferred based on values from the
element tuple (correct algebraic alternative in the type domain would be
to use `zero(eltype(a))` rather than `one(eltype(a))`, but this wouldn't
work for arrays inside static arrays.)
Should fix a bug reported on slack by @pablosanjose

Fix `diff` of nested static arrays

---

src/abstractarray.jl

Hat tip to @MasonProtter for this neat little trick.
This PR eliminates allocations in `SVector` containers that hold a single bits eltype and speeds them up by 1000 times the speed of the base branch in some cases:
_base branch:_
```julia
julia> @benchmark reverse($v)
BenchmarkTools.Trial: 
memory estimate:  486.89 KiB
allocs estimate:  20699
--------------
minimum time:     536.714 μs (0.00% GC)
median time:      540.254 μs (0.00% GC)
mean time:        567.529 μs (1.55% GC)
maximum time:     1.777 ms (65.64% GC)
--------------
samples:          8788
evals/sample:     1
```
_sc/reverse-speedup:_
```julia
julia> @benchmark reverse($v)
BenchmarkTools.Trial: 
memory estimate:  0 bytes
allocs estimate:  0
--------------
minimum time:     31.943 ns (0.00% GC)
median time:      32.063 ns …
```

Generate `reverse` for `StaticVector` types

---

src/svd.jl
test/svd.jl

This workaround allows the LinearAlgebra implementation of `pinv` to be
inferred on julia 1.5-rc1 and 1.6-DEV. Unfortunately the extra inline
annotation doesn't seem to work on lower Julia versions.
Fixes #803 on newer Julia versions

Ensure `full` is constant propagated in `svd(A,full=false)`

---

src/convert.jl
test/ambiguities.jl
test/convert.jl

This PR fixes a method ambiguity in StaticArrays.jl. I found it while testing my package (which depends on StaticArrays.jl) with [Aqua.jl](https://github.com/JuliaTesting/Aqua.jl) and it popped up because I was overloading `convert` (for something completely unrelated).
Before this PR:
```julia
julia> Scalar{Int}[SVector{1,Int}(3)]
ERROR: MethodError: convert(::Type{Scalar{Int64}}, ::SVector{1,Int64}) is ambiguous. Candidates:
convert(::Type{SA}, a::AbstractArray) where SA<:(Scalar{T} where T) in StaticArrays at /home/liozou/.julia/dev/StaticArrays/src/Scalar.jl:12
convert(::Type{SA}, sa::StaticArray) where SA<:StaticArray in StaticArrays at /home/liozou/.julia/dev/StaticArrays/src/convert.jl:10
Possible fix, define
convert(::Type{SA}, ::StaticArray) where …
```

Resolve ambiguity for `convert(::Type{<:Scalar}, ::StaticArray)`

---

test/ambiguities.jl
test/core.jl
test/matrix_multiply_add.jl

This (hopefully) turns the angry red cross into a nice green tick.
There are two separate commits, with two distinct goals:
- the first commit is a genuine test fix for julia versions >= v1.6, which reflects https://github.com/JuliaLang/julia/pull/36107
- the second commit is not a fix, it just marks as `@test_broken` what has been broken for a few months now on julia versions >= v1.5. I tried to correctly fix this issue but `@code_typed mul!(c,A,b)` yields the same thing on v1.4 and v1.5 while `@code_llvm mul!(c,A,b)` is different, so I have no idea how to fix it, sorry.
(The second commit is in direct conflict with https://github.com/JuliaArrays/StaticArrays.jl/pull/783/commits/6e0936f0f0361e5330a0fe780ea687eff48fce1d so https://github.com/JuliaArrays/StaticArrays.jl/pull/783 will have …

Fix nightly CI tests

---

src/abstractarray.jl
test/abstractarray.jl

Currently we already have `eachindex(SA[1, 2, 3, 4]) isa SOneTo` for
vectors but not for matrices. This changes makes `eachindex` consistent.

use `SOneTo` for `eachindex()`

---

src/abstractarray.jl

Here is one possible take on #821.

Avoid type piracy in similar

---

src/MArray.jl
src/SizedArray.jl
src/matrix_multiply_add.jl
test/SizedArray.jl
test/abstractarray.jl
test/matrix_multiply_add.jl

Allocation-free statically sized views in Julia 1.5 🎉
The code should be more-or-less complete but I need to add more tests.
One thing that is potentially controversial (and subject to change) is allowing one way of reshaping. Sometimes I represent arrays of different sizes as parts of a long 1-dimensional array, I could of course call `reshape` before wrapping in `SizedArray` but that's easy enough to do directly in `SizedArray`, and currently `SizedArray` allows for even more reshaping. Relevant PR: #666.
This PR supersedes #341 .

Sized AbstractArray

---

src/abstractarray.jl
test/abstractarray.jl

Before this, it returned an MMatrix:
```
julia> rot180(SA[1 2; 3 4])
2×2 MMatrix{2, 2, Int64, 4} with indices SOneTo(2)×SOneTo(2):
4  3
2  1
julia> @btime rot180(m)  setup=(m=@SMatrix rand(5,5));
12.852 ns (1 allocation: 208 bytes)
```
Afterwards, `4.373 ns (0 allocations: 0 bytes)`. (But no quicker for `rotl90`.)

Add `rot180` etc. for SMatrix

---

src/cholesky.jl
test/chol.jl

You can benchmark the implementation in this PR versus the current `StaticArray`s by having the current `StaticArray`s installed and running the following script:
```julia
using StaticArrays, LinearAlgebra
@generated function uchol(A::SMatrix{M,M,T}) where {M,T}
q = Expr(:block)
for n in 1:M
for m ∈ n:M
r = Expr(:ref, :A, n, m)
ln = LineNumberNode(@__LINE__,Symbol(@__FILE__))
r = Expr(:macrocall, Symbol("@inbounds"), ln, r)
push!(q.args, Expr(:(=), Symbol(:L_,m,:_,n), r))
end
for k ∈ 1:n-1, m in n:M
L_m_n = Symbol(:L_,m,:_,n)
push!(q.args, Expr(:(=), L_m_n, Expr(:call, :muladd, Expr(:call, :(-), Symbol(:L_,m,:_,k)), Symbol(:L_,n,:_,k), L_m_n)))
end
L_n_n = Symbol(:L_,n,:_,n)
push!(q.args, Expr(:(=), L_n_n, :sqrt, L_n_n)))
Linv_n_n = Symbol(:Linv_,n,:_,n)
push!(q.args, Expr(:(=), Linv_n_n, …
```

Updated _cholesky function.

---

src/triangular.jl
test/triangular.jl

I've added right division by triangular matrices, division of structured matrices and removed some related dead code.

More general division by triangular matrices

---

src/MArray.jl
src/MMatrix.jl
src/MVector.jl
src/SArray.jl
src/SMatrix.jl
src/SVector.jl
src/SizedArray.jl
test/MArray.jl
test/MMatrix.jl
test/MVector.jl
test/SArray.jl
test/SMatrix.jl
test/SVector.jl
test/SizedArray.jl

Maybe not the prettiest solution but still fixes #557 and #782.

Fixing constructors from 0-element arrays

---

src/broadcast.jl
test/broadcast.jl

Correctly find size of non-homogenous tuples in broadcast_size

---

src/traits.jl
src/util.jl

There's two changes here:
1. Drop unnecessary `<:` in Vararg. Tuples are already covariant and this form will be deprecated.
2. Use Base.unwrapva, rather than open coding the equivalent, since the implementation will change.
With this change, everything should work with or without https://github.com/JuliaLang/julia/pull/38136.

Adjust to upcoming Base Vararg change

---

src/abstractarray.jl
test/abstractarray.jl

This makes the new lhs slurping syntax return an `S/MVector` if the rhs is an `S/MArray`. See JuliaLang/julia#37410

overload Base.rest

---

src/SizedArray.jl
test/SizedArray.jl

Things like iteration currently fail for SizedArrays with offset axes, so I think it's better to error right array. See https://github.com/JuliaArrays/StaticArrays.jl/pull/844#issuecomment-717598756

require one-based indexing for SizedArray

---

src/linalg.jl
test/linalg.jl

* Implement the trivial diagm(v) for zeroth diagonal
* Make diagm use similar_type for the output
* Avoid calling problematic generic functions within the generator body
(including promote_type)
Fixes #834

Various fixes for `diagm`

---

Project.toml
src/matrix_multiply_add.jl

This PR is an attempt at fixing #857.
Briefly, `StaticVecOrMatLike` is a very large union, and this caused Julia 1.0.x 
to use a large amount of memory when compiling StaticArrays in the presence of 
other packages that also extend `LinearAlgebra.mul!` in a similar fashion. As an 
example, this led to JuMP using more than 4 GB of RAM when running `using JuMP`, 
causing its CI to crash.
Computing the eltypes within the function, rather than specifying them in the 
type arguments greatly improves the issue, with `using JuMP` going from:
julia> @time using JuMP
[ Info: Precompiling JuMP [4076af6c-e467-56ae-b986-b466b2749572]
Killed
to:
julia> @time using JuMP
[ Info: Precompiling JuMP [4076af6c-e467-56ae-b986-b466b2749572]
97.868305 seconds (12.75 M allocations: 805.413 MiB, 0.30% gc time) …

Add a work-around on Julia 1.0 for #857

---

Project.toml
src/MArray.jl
src/SizedArray.jl
test/SizedArray.jl

The added tests don't work on current master. They're in the `SizedArray` tests file because views of `MArray`s create a `SizedArray` wrapper.

Define elsize to make `pointer` more reliable.

---

src/SizedArray.jl
test/SizedArray.jl

While working on https://github.com/mateuszbaran/HybridArrays.jl/issues/31 I noticed that the code for calculating size of views of `SizedArray` doesn't work for some subtypes of `StaticVector`. This PR fixes this problem.

Better handling of subtypes of StaticVector in views of SizedArray

---

src/indexing.jl
test/indexing.jl

Looking at the history, this is pretty old code, and the special case
`v <: StaticArray` seems unnecessary now — the compiler should have no
trouble computing `length(v)` as a constant and eliminating the branch
when `v` is a static array.
Fixes #866

Bugfix: newsize not defined in error message

---

test/indexing.jl

Strangely enough the tests from #868 were broken with a misplaced paren, but CI appeared to have passed on that PR (other than nightly which failed due to upstream changes)  No idea what happened there...

Fix tests from #868

---

src/sort.jl
test/sort.jl

We reverse the order as part of the bitonic sort algorithm, but
`ReverseOrdering` is not the true reverse order for an order `::Perm`.
This led to non-stable sorting for `sortperm`.
Fixed by hand-wiring the reversal.
Fixes #858.

sort: avoid use of `ReverseOrdering` for `BitonicSort`

---

docs/Project.toml
docs/make.jl
src/deque.jl

* Fix #870 to deploy the document on github pages.
* Fix jldoctests

Maintenance around Documenter.jl

---

src/cholesky.jl
test/chol.jl

4x4 cholesky factor is more or less the same fast before:
```julia
julia> @benchmark cholesky(Symmetric($(Ref(Sa))[]))
BenchmarkTools.Trial:
memory estimate:  0 bytes
allocs estimate:  0
--------------
minimum time:     8.304 ns (0.00% GC)
median time:      8.556 ns (0.00% GC)
mean time:        8.628 ns (0.00% GC)
maximum time:     13.635 ns (0.00% GC)
--------------
samples:          10000
evals/sample:     999
```
as after
```julia
julia> @benchmark cholesky(Symmetric($(Ref(Sa))[]))
BenchmarkTools.Trial:
memory estimate:  0 bytes
allocs estimate:  0
--------------
minimum time:     8.305 ns (0.00% GC)
median time:      8.620 ns (0.00% GC)
mean time:        8.739 ns (0.00% GC)
maximum time:     28.546 ns (0.00% GC)
--------------
samples:          10000
evals/sample:     999
```
I didn't …

Added check option to cholesky

---

docs/make.jl

The document deployment is still failing. (see #870, #872, [gh-pages branch](https://github.com/JuliaArrays/StaticArrays.jl/tree/gh-pages))
Here's a screenshot from [github actions](https://github.com/JuliaArrays/StaticArrays.jl/runs/2211769463?check_suite_focus=true).
This seems because of [this commit](https://github.com/JuliaArrays/StaticArrays.jl/pull/872/commits/5ed6b41ca9125d216ec5454df146541376ad98f8), and I've fixed it.
@fredrikekre
Do you have any ideas?

Fix url in docs/make.jl to deploy document

---

Project.toml
src/matrix_multiply.jl
test/matrix_multiply.jl

This fixes issue #894 and adds some test to make sure it remains correct.

fix for issue #894

---

Project.toml
src/linalg.jl
test/linalg.jl

Also provide a unary + operator.
Closes https://github.com/JuliaArrays/StaticArrays.jl/issues/899.

Make scalar multiplication type stable

---

Project.toml
src/SArray.jl
src/abstractarray.jl
test/SArray.jl
test/SVector.jl

Since `SArrays` are immutable and support allocation-less vector indexing for certain index types, views of `SArray`s constructed with such indices do not need to retain the `SubArray` wrapper and may just return another `SArray` obtained through indexing. Fixes #892.
After this PR:
```julia
julia> s = SMatrix{3,3}(ones(3,3));
julia> sv = @view s[:, :]
3×3 SMatrix{3, 3, Float64, 9} with indices SOneTo(3)×SOneTo(3):
1.0  1.0  1.0
1.0  1.0  1.0
1.0  1.0  1.0
julia> @btime $(Ref(sv))[] + $(Ref(sv))[]
3.730 ns (0 allocations: 0 bytes)
3×3 SMatrix{3, 3, Float64, 9} with indices SOneTo(3)×SOneTo(3):
2.0  2.0  2.0
2.0  2.0  2.0
2.0  2.0  2.0
```

Views of SArray may use getindex to avoid the SubArray wrapper

---

Project.toml
src/abstractarray.jl
test/SArray.jl

I'm not too sure if these are too internal to `Base`, but with this PR the following work now:
```julia
julia> S = SMatrix{1, 2, Int, 2}(1, 2)
1×2 SMatrix{1, 2, Int64, 2} with indices SOneTo(1)×SOneTo(2):
1  2
julia> reshape(S, Val(1))
2-element SVector{2, Int64} with indices SOneTo(2):
1
2
julia> reshape(S, Val(3))
1×2×1 SArray{Tuple{1, 2, 1}, Int64, 3, 2} with indices SOneTo(1)×SOneTo(2)×SOneTo(1):
[:, :, 1] =
1  2
julia> @view S[1,1,1]
0-dimensional view(::SArray{Tuple{1, 2, 1}, Int64, 3, 2}, 1, 1, 1) with eltype Int64:
1
```

reshape with Val

---

Project.toml
src/broadcast.jl
test/broadcast.jl

Broadcasting operations involving Diagonal StaticArrays now preserve the size information.
On master:
```julia
julia> Diagonal(SVector{2}(1:2)) .* SVector{2}(1:2)
2×2 Matrix{Int64}:
1  0
0  4
julia> SVector{2}(1:2) .* Diagonal(SVector{2}(1:2)) .* SVector{2}(1:2)
2×2 Matrix{Int64}:
1  0
0  8
```
After this PR:
```julia
julia> Diagonal(SVector{2}(1:2)) .* SVector{2}(1:2)
2×2 SMatrix{2, 2, Int64, 4} with indices SOneTo(2)×SOneTo(2):
1  0
0  4
julia> SVector{2}(1:2) .* Diagonal(SVector{2}(1:2)) .* SVector{2}(1:2)
2×2 SMatrix{2, 2, Int64, 4} with indices SOneTo(2)×SOneTo(2):
1  0
0  8
```

broadcasting for Diagonal StaticArrays

---

.github/workflows/ci.yml
test/abstractarray.jl
test/ambiguities.jl
test/arraymath.jl
test/svd.jl
test/testutil.jl

I noticed that CI wasn't running on 1.6, which I figured would be a good idea, even if it increases the run-time.
With this PR, it still doesn't run on 1.5, and won't run on 1.6 after 1.7 is released (then it'll run on 1.7) - but it seems better than not to run at all, and doesn't increase CI time very much compared to adding everything.

Run CI on latest released 1.x version

---

Project.toml
src/lu.jl
src/qr.jl
test/lu.jl
test/qr.jl

This basically does just what #921 did to fix #920 for #931; i.e., removes the ambiguity for `qr`.
While doing that, I noticed that #921 hadn't completely resolved the ambiguity for `lu`; e.g., if called as `lu(A, Val(false))` there would still be an ambiguity error; so I fixed that as well. Similarly, I believe it would previously have been ambiguous if provided with a `check` keyword argument.
Added a few tests as well.

Fix method ambiguity for `qr` (#931) and lingering ambiguities for `lu`

---

Project.toml
src/abstractarray.jl
test/abstractarray.jl
test/broadcast.jl

This is an attempt to fix the issue described in https://github.com/JuliaArrays/StaticArrays.jl/pull/907 . I've tried to make changes as limited as possible, so `reshape(::AbstractArray, ::Size)` still makes a copy. I can change that but doing so is not essential to fixing the key problem, that is `reshape(::StaticArray, ::SOneTo...)` making a copy, which is fixed here.
This looks like a change that may have some impact on downstream packages so I hope to get some feedback :slightly_smiling_face: .
cc @KristofferC @dlfivefifty @andyferris .

Fix reshaping of a mutable StaticArray

---

docs/src/pages/api.md

Mention `StaticArrays.sacollect` in the docs.

Document sacollect.

---

Project.toml
src/SUnitRange.jl
test/SUnitRange.jl

This allows recovery of containers etc with `SUnitRange` from printed output.
Cf [discussion](https://discourse.julialang.org/t/print-sunitrange-within-tuple-as-is-not-as-a-vector/64678/).

Add a two-argument show method for SUnitRange.

---

Project.toml
src/linalg.jl
test/linalg.jl

This closes the issue noted in #915, i.e. the following now works:
```jl
a  = SA[SA[1, 2], SA[3, 4]]
norm(a)
```
which threw before. It also fixes a similar issue for the "p"-`norm`.
This also fixes a few other issues with `norm` and friends:
- Previously, the implementation of both the `norm` and "p"-`norm` were susceptible to integer overflow because they didn't convert to float early. They do now. This reduces performance a slight bit for `::SVector{Int}` but that seems preferable to quietly overflowing.
- Previously, the "p"-`norm` implementation was type-unstable for `SVector{Int}` inputs (sometimes returning `Float64` sometimes `Int`, depending on `p`). It now always returns a floating point value, consistently with Base.

Fixes to `norm` and friends (closes #915)

---

Project.toml
src/abstractarray.jl
test/abstractarray.jl

Before:
```
julia> permutedims(SA[1,2,3])
1×3 reshape(::SVector{3, Int64}, 1, 3) with eltype Int64:
1  2  3
julia> axes(ans)
(Base.OneTo(1), Base.OneTo(3))
julia> permutedims(SA[1 2; 3 4])
2×2 MMatrix{2, 2, Int64, 4} with indices SOneTo(2)×SOneTo(2):
1  3
2  4
```
After:
```
julia> permutedims(SA[1,2,3])
1×3 SMatrix{1, 3, Int64, 3} with indices SOneTo(1)×SOneTo(3):
1  2  3
julia> permutedims(SA[1 2;3 4])
2×2 SMatrix{2, 2, Int64, 4} with indices SOneTo(2)×SOneTo(2):
1  3
2  4 
```
Unchanged are all the cases taking `perm`, discussed in #806.
```
julia> permutedims(@SArray(rand(1,2,3)), (3,2,1))
3×2×1 MArray{Tuple{3, 2, 1}, Float64, 3, 6} with indices SOneTo(3)×SOneTo(2)×SOneTo(1):
```
~~I'm not too sure what should happen for MArrays or SizedArrays.~~

`permutedims` for vectors and matrices

---

Project.toml
src/linalg.jl
test/linalg.jl

This avoids hitting the general fallback https://github.com/JuliaLang/julia/blob/5118a1babf9d2963f31e98e427cc99a969d5ca46/base/math.jl#L1167 
Depending on the processor, LLVM can turn this into efficient FMA calls. Depending on the workload, this can speed-up number crunching quite a bit.
I increased the version number since I would really like to be able to use this performance improvement.

specialize muladd

---

Project.toml
src/linalg.jl
test/linalg.jl

Fixes #887 in the simplest way possible.
Note that the existing `normalize` implementation doesn't have many guard-rails (e.g., no over/underflow detection) and `normalize!` has some rough edges (e.g., doesn't work for arrays with `Int` eltype) - but I figured I'd just keep this to the scope of #887.

Expand signature of `normalize` from `StaticVector` to `StaticArray` (fixes #887)

---

src/precompile.jl

I was doing some profiling with SnoopCompile of a package of mine and this method came up as somewhat expensive - I figured this might be worth fixing here since that operation is likely to be widely used by users of StaticArrays.

Add a precompile for `(*)(::SMatrix, ::SVector)`

---

src/SMatrix.jl
src/matrix_multiply_add.jl

These improve inferrence to guard against very minor invalidations
from packages that extend `==`.

Small tweaks to prevent `==` invalidation

---

test/mapreduce.jl

In preparation for https://github.com/JuliaLang/julia/pull/41885

Generalize exception type

---

src/abstractarray.jl
test/abstractarray.jl

On master
```julia
julia> s1 = SA[1,2];
julia> s2 = SA[1,2,3];
julia> v = [s1, s2];
julia> f(v, i) = length(v[i]);
julia> @code_warntype f(v, 1)
Variables
#self#::Core.Const(f)
v::Vector{SArray{S, Int64, 1, L} where {S<:Tuple, L}}
i::Int64
Body::Any
1 ─ %1 = Base.getindex(v, i)::SArray{S, Int64, 1, L} where {S<:Tuple, L}
│   %2 = Main.length(%1)::Any
└──      return %2
```
After this PR
```julia
julia> @code_warntype f(v, 1)
Variables
#self#::Core.Const(f)
v::Vector{SArray{S, Int64, 1, L} where {S<:Tuple, L}}
i::Int64
Body::Int64
1 ─ %1 = Base.getindex(v, i)::SArray{S, Int64, 1, L} where {S<:Tuple, L}
│   %2 = Main.length(%1)::Int64
└──      return %2
```

Add type-assertions to length to help with inference

---

src/StaticArrays.jl
src/convert.jl
test/convert.jl

This just implements the suggestion in #935 for `SArray` and `MArray` and includes some tests.
I put the definitions in `src/convert.jl` - but let me know if they fit better elsewhere.

implement `float` and `real` for `StaticArray` (fix #935)

---

docs/src/index.md
docs/src/pages/quickstart.md
src/MArray.jl
src/MVector.jl
src/SArray.jl
src/SVector.jl
test/MVector.jl
test/SVector.jl

Having access with v.x etc makes the *concrete* SVector interface much
more usable for geometry; indeed, it will "just work like you expect"
without the need to resort to a custom FieldVector type.
This makes the *concrete* SVector/MVector interface fatter, but OTOH I
don't think it can do any harm to people who don't want to use it.
If we do this, it should be made to work at least for SVector{1}
SVector{2} and SVector{3}, but I saw no reason to disallow the use of
these in higher dimensions and overcomplicate the implementation.
Inspired by discussion at
https://discourse.julialang.org/t/ray-tracing-in-a-week-end-julia-vs-simd-optimized-c/72958
I'll add tests and some docs if we decide this is a good idea!

Named access with .{x,y,z} to elements of SVector and MVector

---

docs/src/pages/api.md

Since #980 allows named access to `SVector` fields, this should be noted in the `FieldVector` docs so that users realize that they don't need a `FieldVector` for these particular names.

note named access for SVector in FieldVector docs

---

src/linalg.jl

The `conj` method is defined for `AbstractArray` in `Base`, and this seems not necessary in StaticArrays.jl.
https://github.com/JuliaLang/julia/blob/master/base/abstractarraymath.jl#L120

Remove `conj` method

---

Project.toml
src/linalg.jl
test/linalg.jl

This avoids hitting the general fallback https://github.com/JuliaLang/julia/blob/5864e4341b0f11879a566bb6dbc571e230c26691/base/fastmath.jl#L265
Depending on the processor, LLVM can turn this into efficient FMA calls. Depending on the workload, this can speed-up number crunching quite a bit. For example I get
```julia
julia> foo_add(a, b, c) = @fastmath a * b + c
foo_add (generic function with 1 method)
julia> foo_sub(a, b, c) = @fastmath a * b - c
foo_sub (generic function with 1 method)
julia> a = 1.5; b = SVector(1.0, 2.0, 3.0, 4.0); c = SVector(1.0, 2.0, 3.0, 4.0);
julia> @code_native debuginfo=:none foo_add(a, b, c)
.text
movq    %rdi, %rax
vbroadcastsd    %xmm0, %ymm0
vmulpd  (%rsi), %ymm0, %ymm0
vaddpd  (%rdx), %ymm0, %ymm0
vmovupd %ymm0, (%rdi)
vzeroupper …
```

specialize `mul_fast` and `add_fast` to allow FMA

---

Project.toml
src/SArray.jl
src/SHermitianCompact.jl
src/StaticArrays.jl
src/util.jl

`@_inline_meta` is deprecated in 1.8-DEV.
```console
$ julia1.8 --depwarn=error --project -e 'using StaticArrays; zeros(SVector{3,Int})'
ERROR: LoadError: `@_inline_meta` is deprecated, use `@inline` instead.
```
This patch defines `const var"@_inline_meta" = Base.var"@inline"` for 1.8-DEV.
It also removes the import of unused macro `@_pure_meta`.

Avoid using deprecated macro `@_inline_meta`

---

src/mapreduce.jl
test/mapreduce.jl

A colleague noticed the following inconsistency in the output types:
```julia
julia> struct Vec3{T} <: FieldVector{3, T}
x::T
y::T
z::T
end
julia> StaticArrays.similar_type(::Type{<:Vec3}, ::Type{T}, s::Size{(3,)}) where {T} = Vec3{T}
julia> v3 = Vec3(1, 2, 3); v = [1, 2, 3];
julia> v3 + v
3-element Vec3{Int64} with indices SOneTo(3):
2
4
6
julia> v + v3
3-element SVector{3, Int64} with indices SOneTo(3):
2
4
6
```
With this patch `similar_type` is called on the first argument that is `<: StaticArray`, which is actually consistent with the 0-dimensional case: https://github.com/JuliaArrays/StaticArrays.jl/blob/1858207b405ea168ecd6810ffa7bbb07e984a2b7/src/mapreduce.jl#L62

map: build output type based on first static argument.

---

Project.toml
src/eigen.jl
test/eigen.jl

As in the title, currently `eigvals` doesn't work for complex 3x3 matrices (see test for an example). This fixes the problem.

Fix eigvals for complex 3x3 matrices

---

.github/workflows/benchmark.yml
.github/workflows/ci.yml
Project.toml
benchmark/bench_matrix_ops.jl
docs/src/index.md
src/SizedArray.jl
src/StaticArrays.jl
src/abstractarray.jl
test/SHermitianCompact.jl
test/SizedArray.jl
test/abstractarray.jl
test/accumulate.jl
test/ambiguities.jl
test/chol.jl
test/core.jl
test/eigen.jl
test/linalg.jl
test/matrix_multiply_add.jl
test/svd.jl
test/testutil.jl

We discussed this briefly on Slack: now that the new Julia LTS is v1.6, it would make sense to drop support for earlier versions. There's at least two good reasons for doing so: 
1. CI takes forever to run when it needs to go through so many Julia versions.
2. Development becomes tedious and somewhat fragile because one has to guard what may or may not work on different Julia versions. As a result, there's a lot of `VERSION` checks in StaticArrays currently (in source files and in tests).
I'm putting this up mainly for discussion - but the relevant bits to actually do this should also be here and are split across independent commits. 
I also bumped the minor version of StaticArrays to v1.4: quoting @c42f from Slack:
> [...] we can release patches versions 1.3.x if really necessary for …

Drop support for versions of Julia lower than v1.6

---

.github/workflows/benchmark.yml
benchmark/bench_mat_mul.jl
benchmark/bench_qr.jl

Following up on https://github.com/JuliaArrays/StaticArrays.jl/pull/985#issuecomment-1046936674 (cc. @KristofferC), this changes the benchmarks to run on the latest released version of Julia.
Additionally, it reduces the amount of benchmarking done for large matrices: those benchmarks currently take up the majority of benchmarking time due to their large compilation time, which doesn't seem worthwhile given that using StaticArrays for such large matrices is effectively counter to the package's focus on small sizes.

Benchmark on latest Julia and scale back large-matrix benchmarking

---

src/lu.jl
src/qr.jl
test/lu.jl
test/qr.jl

This tackles the same problem as #977 (and builds on it), but applies it to `qr` as well, and should also work on Julia v1.6, where the new `LinearAlgebra.PivotingStrategy` is not defined.
At the same time, I added accessors so that `qr(::StaticArray, pivot)` and `lu(...)` can be called with `pivot <: PivotingStrategy` instances.
Closes #977.

Fix `lu`/`qr` pivot deprecations and allow `PivotingStrategy` input

---

src/SizedArray.jl
test/MMatrix.jl
test/MVector.jl
test/SizedArray.jl

This fixes the following:
```julia
julia> sa = SizedVector{2}([1,2]);
julia> setindex!(sa, 99, 1)  # doesn't return the array itself, like Base does
2-element Vector{Int64}:
99
2
julia> sa
2-element SizedVector{2, Int64, Vector{Int64}} with indices SOneTo(2):
99
2
```
For a SizedMatrix there is no problem, nor for an MArray. But this also adds tests for those cases.

Fix return type for `setindex!(::SizedArray, ...)`

---

Project.toml
src/broadcast.jl
src/precompile.jl
test/broadcast.jl

This PR tries to make the current broadcast kernal reusable to more wrapped StaticArray. 
For this goal, we need to get `first_staticarray` outside the `@generated function` to make sure the type match extendable. (Not sure the reason)
Our optimizer should be clever enough to make it zero cost at runtime.
This was discussed in https://github.com/JuliaArrays/StructArrays.jl/pull/215, where we want to make 
```julia
s = StructArray{ComplexF64}((SVector(1., 2., 3.), SVector(0., 0., 0.)))
log.(s)
```
return a `SVector`.
A simple test has been added.

Make `broadcast` extendable to user array wrapper.

---

test/qr.jl

Failure example is [here](https://github.com/JuliaArrays/StaticArrays.jl/runs/5522395851?check_suite_focus=true) and occurs because of a change to the element type of heterogeneous vectors of arrays (cf. https://github.com/JuliaLang/julia/issues/44586).
The change here just makes the tests loop over a tuple rather than an array (to make sure the element type is unchanged).

Fix qr test failure on nightly

---

src/abstractarray.jl
src/broadcast.jl
src/precompile.jl
test/broadcast.jl

This PR tries to perform `combine_size` during `Broadcast.instantiate`:
1. For `broadcast`, `combine_axes` will return a `Tuple{Vararg{SOneTo}}`, thus the output size has been static.
2. For `broadcast!`, the `dest`'s `axes` is marked as static (if possible). If there's no size-1 dim in `src`. The current generated kernal will be called.
With this change, we can reduce the compile time for first broadcast by about 1/4:
```julia
julia> a = @SArray zeros(3,3)
3×3 SMatrix{3, 3, Float64, 9} with indices SOneTo(3)×SOneTo(3):
0.0  0.0  0.0
0.0  0.0  0.0
0.0  0.0  0.0
julia> @time a .+ a;
0.234903 seconds (452.90 k allocations: 24.654 MiB, 99.75% compilation time) #  on master: 0.308612 seconds (513.89 k allocations: 27.912 MiB, 99.87% compilation time)
```

Drop `combine_size`

---

Project.toml
src/FieldArray.jl
src/MArray.jl
src/MMatrix.jl
src/MVector.jl
src/SArray.jl
src/SHermitianCompact.jl
src/SMatrix.jl
src/SVector.jl
src/Scalar.jl
src/SizedArray.jl
src/convert.jl
src/util.jl
test/FieldMatrix.jl
test/FieldVector.jl
test/MArray.jl
test/MMatrix.jl
test/MVector.jl
test/SArray.jl
test/SHermitianCompact.jl
test/SMatrix.jl
test/Scalar.jl
test/SizedArray.jl
test/ambiguities.jl
test/convert.jl
test/empty_array_syntax.jl

Seperated from #1009.
This PR aims to unify the implement of `StaticArray`'s constructor with a new method `construct_type`.
It returns a `concrete` constructor based on `src <: Union{Tupe, StaticArray, AbstractArray}` and the target type `SA` (if possible).
e.g.
```julia
julia> StaticArrays.construct_type(SMatrix{2},(1,2,3,4))
SMatrix{2, 2, Int64} (alias for SArray{Tuple{2, 2}, Int64, 2})
julia> StaticArrays.construct_type(SMatrix{2},(1.,2,3,4))
SMatrix{2, 2, Float64} (alias for SArray{Tuple{2, 2}, Float64, 2})
julia> StaticArrays.construct_type(SMatrix,(1.,2,3,4)) # the output's size is not static.
ERROR: DimensionMismatch: No precise constructor for SMatrix found. Length of input was 4.
```
Thus, we only need to mannually define the constructor with precise `size`, `eltype` and …

Code clean and reuse for `constructor`.

---

src/SOneTo.jl
test/abstractarray.jl

Based on https://github.com/JuliaArrays/StaticArrays.jl/issues/881#issuecomment-812822965, this partially addresses the issue of reduction on wrappers of `StaticArray`s.
Currently,
```julia
julia> s = SArray{Tuple{2,2,2},Int,3,8}((1,2,3,4,5,6,7,8))
2×2×2 SArray{Tuple{2, 2, 2}, Int64, 3, 8} with indices SOneTo(2)×SOneTo(2)×SOneTo(2):
[:, :, 1] =
1  3
2  4
[:, :, 2] =
5  7
6  8
julia> ss = StructArray{Complex{Int}}((s,s))
2×2×2 StructArray(::SArray{Tuple{2, 2, 2}, Int64, 3, 8}, ::SArray{Tuple{2, 2, 2}, Int64, 3, 8}) with eltype Complex{Int64} with indices SOneTo(2)×SOneTo(2)×SOneTo(2):
[:, :, 1] =
1+1im  3+3im
2+2im  4+4im
[:, :, 2] =
5+5im  7+7im
6+6im  8+8im
julia> sum(ss, dims=1)
ERROR: ArgumentError: No method is implemented for reducing index range of type SOneTo{2}. Please implement …
```

Specialize reduced_indices for Tuple{Vararg{SOneTo}}

---

src/MArray.jl
test/MArray.jl

Currently, `Base.elsize(<:Type{<:MArray})` is not correct for eltypes for which `sizeof` is not a multiple of `Base.datatype_alignment`. This leads to `pointer(::MArray, ::Int)` giving incorrect addresses. For example:
```julia
julia> primitive type Test24 24 end
julia> Test24(n) = Base.trunc_int(Test24, n);
julia> a = Test24.(1:4);
julia> m = MVector{4}(a)
4-element MVector{4, Test24} with indices SOneTo(4):
Test24(0x000001)
Test24(0x000002)
Test24(0x000003)
Test24(0x000004)
julia> GC.@preserve m unsafe_load.(pointer.(Ref(m), 1:4))
4-element Vector{Test24}:
Test24(0x000001)
Test24(0x0002be)
Test24(0x030000)
Test24(0x000000)
```
This PR fixes this by calling `Base.elsize` on the corresponding `Vector` type. (This issue was previously present in Base …

Fix Base.elsize(<:Type{<:MArray})

---

src/det.jl

The SMatrix{4,4} `det` code (added in #260) performs 72 multiplications and 23 addition/subtractions.  Rewriting as products of 2x2 minors reduces to 30 multiplications and 17 additions/subtractions.  Benchmarking (below) shows performance improvement from 11ns to <5ns, commensurate with the decrease in operations.
I see that in pull request #597 @ryanelandt (with the approval of @andyferris) implicitly rewrote `inv` using 2x2 minors.  Thus, my pull request just extends the performance improvement to `det`.  
-------
```julia
julia> using BenchmarkTools, Random, LinearAlgebra                                                        
julia> using StaticArrays                                                                                 
[ Info: Precompiling StaticArrays …
```

Rewrite 4x4 det as product of 2x2 minors for improved performance

---

src/linalg.jl
test/linalg.jl

This PR fixes https://github.com/JuliaArrays/StaticArrays.jl/issues/1066.
**Before this PR**
```julia
julia> n = SMatrix{0,0,Float64}()
0×0 SMatrix{0, 0, Float64, 0} with indices SOneTo(0)×SOneTo(0)
julia> adjoint(n)
0×0 SMatrix{0, 0, Union{}, 0} with indices SOneTo(0)×SOneTo(0)
julia> transpose(n)
0×0 SMatrix{0, 0, Union{}, 0} with indices SOneTo(0)×SOneTo(0)
julia> n/n
ERROR: MethodError: one(::Type{Union{}}) is ambiguous. Candidates:
one(::Union{Type{T}, T}) where T<:AbstractString in Base at strings/basic.jl:262
one(::Union{Type{P}, P}) where P<:Dates.Period in Dates at /home/hyrodium/julia/julia-1.7.3/share/julia/stdlib/v1.7/Dates/src/periods.jl:54
one(::Type{SM}) where SM<:(Union{LinearAlgebra.Adjoint{T, <:Union{StaticArray{Tuple{var"#s2"}, T, 1} where …
```

Fix `adjoint` and `transpose` for 0×0 matrix

---

test/FieldMatrix.jl
test/FieldVector.jl
test/ambiguities.jl

This PR reduces ambiguities `detect_ambiguities(StaticArrays)`. Note that the most of ambiguities were introduced in `test/FieldMatrix.jl` and `test/FieldVector.jl`.
We have the following two options, but this PR will minimize the changes for now.
* Drop `test/ambiguities.jl` and introduce Aqua.jl
* Duplicate `addtests("ambiguities.jl")` into `group-B` in `runtests.jl` and make sure no more ambiguities were not introduced during the test.

Reduce ambiguities

---

src/indexing.jl

This pull request closes #1065 by throwing a better error when attempting to mutate a `StaticArray`
```julia
julia> SVector(1, 2, 3)[1] = 2
ERROR: setindex!(::SVector{3, Int64}, value, ::Int) is not defined.
Hint: Use `MArray` to create a mutable static array
```
Note: Julia has an [experimental error hints](https://docs.julialang.org/en/v1/base/base/#Base.Experimental.register_error_hint) but I didn't use them because they're still experimental (and it seemed like too much stuff for a simple error message).

improve error message of `setindex!`

---

Project.toml
src/broadcast.jl
test/broadcast.jl

This PR ports https://github.com/JuliaLang/julia/pull/43322 into `StaticArrays.jl` to make sure our broadcast is stable.
Some modification has been done to make 1.6's compiler happy.
Close #1078, close #560, close #682, close #609, close #797

Improve `broadcast`'s stability

---

src/MArray.jl
src/MMatrix.jl
src/MVector.jl
src/SArray.jl
src/SMatrix.jl
src/SVector.jl
test/SVector.jl

Fix #1042. I'm not sure how to add a test though...

Resolve the identifier conflicts in `@SArray`

---

src/pinv.jl
test/pinv.jl

This PR fixes #1080.
**Before this PR**
```julia
julia> using StaticArrays, LinearAlgebra
julia> pinv([-1 0; 0 -1])
2×2 Matrix{Float64}:
-1.0   0.0
0.0  -1.0
julia> pinv(SA[-1 0; 0 -1])
2×2 SMatrix{2, 2, Float64, 4} with indices SOneTo(2)×SOneTo(2):
0.0  0.0
0.0  0.0
```
**After this PR**
```julia
julia> using StaticArrays, LinearAlgebra
julia> pinv([-1 0; 0 -1])
2×2 Matrix{Float64}:
-1.0   0.0
0.0  -1.0
julia> pinv(SA[-1 0; 0 -1])
2×2 SMatrix{2, 2, Float64, 4} with indices SOneTo(2)×SOneTo(2):
-1.0   0.0
0.0  -1.0
```

Fix bug in `pinv`

---

Project.toml
src/StaticArrays.jl
src/abstractarray.jl
src/broadcast.jl

See https://github.com/JuliaArrays/StaticArraysCore.jl/pull/5
and https://github.com/JuliaArrays/StaticArraysCore.jl/pull/8

Define `similar_type` and `StaticArrayStyle` in the core package.

---

docs/src/pages/api.md

It looks like Julia 0.5 needed some workarounds for broadcasting to be efficient, but I'm pretty sure it's okay to use .+= and ./= in recent versions of Julia. I removed references to Julia 0.5 and 0.6.

Update advice on working with mutable arrays

---

Project.toml
src/FieldArray.jl
test/FieldVector.jl

Stackoverflow is always bad as a error message. This PR tries to make it more informative.
Test added.

Avoid possible stackoverflow in FieldArray's constructor

---

Project.toml
src/StaticArrays.jl
src/traits.jl

Counterpart to https://github.com/JuliaArrays/StaticArraysCore.jl/pull/13

Move `Size` to StaticArraysCore.jl

---

src/SArray.jl
src/SVector.jl
src/matrix_multiply.jl
test/SArray.jl

Some minor nits found with JET.
The point of changes in `src/SVector.jl` and `src/SArray.jl` is that the if-statement otherwise cannot know that the call to `.head` is meaningful (it still thinks that `ex.args[1] isa Any`). This change just splits it up and type-asserts so the knowledge that `ex isa Expr` can propagate. The code duplication is a little annoying, but I couldn't think of a good way to avoid it.
Since it's a macro it doesn't really matter - but I figured it might be nice anyway in order to reduce noise in reports by JET in the future.

nits from JET

---

src/abstractarray.jl

```
inserting isassigned(a::StaticArray, i::Int64...) in StaticArrays at C:\Users\mkitti\.julia\packages\StaticArrays\NOLon\src\abstractarray.jl:31 invalidated:
backedges: 1: superseding isassigned(a::AbstractArray, i::Integer...) in Base at abstractarray.jl:563 with MethodInstance for isassigned(::AbstractMatrix, ::Int64, ::Int64) (4 children)
2: superseding isassigned(a::AbstractArray, i::Integer...) in Base at abstractarray.jl:563 with MethodInstance for isassigned(::AbstractVecOrMat, ::Int64, ::Int64) (4 children)
1 mt_cache
```
Yes it fixes an invalidating function, but it's probably just a good idea to follow Base's convention on this one regardless.

Remove faulty `isassigned` specialization

---

Project.toml
src/StaticArrays.jl
src/mapreduce.jl
test/mapreduce.jl

Implements #1106, at least the basic version when mapping over only that one enumeration.

Mapping over enumeration of a static array

---

Project.toml
src/matrix_multiply_add.jl
test/matrix_multiply_add.jl

This allows `*(A::SizedMatrix{6, 12, Float64, 2, Matrix{Float64}}, D::Diagonal{Float64, MVector{12, Float64}})` to yield a `SizedMatrix` instead of a plain `Matrix`.

Relax diagonal type in matrix-multiply

---

src/linalg.jl
test/linalg.jl

This PR fixes #913 by avoiding underflow in `norm()`.  In the referenced issue, `norm(SA[0, 1e-180])` generates `0.0` instead of the accurate value `1e-180`, because squaring `1e-180` inside `norm()` produces `1e-360`, whose exponent is less than the [smallest exponent allowed in the IEEE double-precision floating point standard](https://en.wikipedia.org/wiki/Double-precision_floating-point_format#Exponent_encoding): `2^-1022 ≈ 1e-308`.  
The standard practice to avoid this underflow is to pre-normalize the vector by its largest-magnitude entry, calculate the norm, and then undo the normalization outside `norm()`:
```julia
vmax = maximum(abs, v)
norm_v = vmax * norm(v ./ vmax)
```
This PR implements the above procedure for `StaticArrays`.  This PR also fixes …

Avoid underflow and overflow in norm()

---

Project.toml
src/arraymath.jl
test/arraymath.jl

Follow up #1122. Fixes https://github.com/JuliaArrays/StaticArrays.jl/issues/1121.
**Before this PR**
```julia
julia> @SMatrix fill(3,2,0)
2×0 SMatrix{2, 0, Union{}, 0} with indices SOneTo(2)×SOneTo(0)
julia> @SMatrix ones(0,2)
0×2 SMatrix{0, 2, Union{}, 0} with indices SOneTo(0)×SOneTo(2)
julia> @SMatrix zeros(0,2)
0×2 SMatrix{0, 2, Union{}, 0} with indices SOneTo(0)×SOneTo(2)
```
**After this PR**
```julia
julia> @SMatrix fill(3,2,0)
2×0 SMatrix{2, 0, Int64, 0} with indices SOneTo(2)×SOneTo(0)
julia> @SMatrix ones(0,2)
0×2 SMatrix{0, 2, Float64, 0} with indices SOneTo(0)×SOneTo(2)
julia> @SMatrix zeros(0,2)
0×2 SMatrix{0, 2, Float64, 0} with indices SOneTo(0)×SOneTo(2)
```

Fix more methods with zero-element array

---

Project.toml
src/linalg.jl
test/broadcast.jl
test/linalg.jl

This is one way to fix #1126, another would be to convert any static array to `SArray` before the norm is calculated. I don't have a strong preference one way or another.

Avoid allocation when computing norm of MVector

---

src/MVector.jl
src/SVector.jl
src/arraymath.jl
test/arraymath.jl

This PR fixes the output values commented on https://github.com/JuliaArrays/StaticArrays.jl/pull/1122#issuecomment-1429146870.
**StaticArrays.jl v1.5.12**
```julia
julia> zero(MVector{3,Any})::MVector{3,Any}
3-element MVector{3, Any} with indices SOneTo(3):
0.0
0.0
0.0
```
**StaticArrays.jl v1.5.13**
```julia
julia> zero(MVector{3,Any})::MVector{3,Float64} # Float64 !== Any
3-element MVector{3, Float64} with indices SOneTo(3):
0.0
0.0
0.0
```
**After this PR**
```julia
julia> zero(MVector{3,Any})::MVector{3,Float64}
ERROR: MethodError: no method matching zero(::Type{Any})
```
I think the return value on v1.5.13 is problematic, but I'm not sure the return value on v1.5.12 is correct because `zero(Any)` throws an error.

Fix zero(SVector{3,Any}) etc. with multiple dispatch

---

Project.toml
src/lu.jl
src/traits.jl
src/triangular.jl

In preparation of https://github.com/JuliaLang/julia/pull/26307.

Avoid second type parameter in `AbstractTriangular`

---

Project.toml
src/convert.jl
test/SVector.jl

If `need_rewrap` returns `true`, then `x` would be re-wrapped before the next call.
Thus there's actually no stackoverflow risk in this case.
fix #1118.

Relax recursion check in `construct_type`

---

.github/workflows/ci.yml
Project.toml
src/lu.jl
src/traits.jl
src/triangular.jl
test/abstractarray.jl
test/ambiguities.jl
test/core.jl
test/det.jl
test/expm.jl
test/inv.jl
test/lu.jl
test/mapreduce.jl
test/matrix_multiply_add.jl
test/qr.jl
test/solve.jl
test/svd.jl

The diff looks exactly like it should. This PR backports some minor changes to the pre-1.0 series, at which many packages are still stuck because of old compat restrictions. I'm convinced, however, that most if not all could bump their compat restriction to v1.x. Without that bump, however, all these packages will stop working on Julia v1.10, after https://github.com/JuliaLang/julia/pull/26307 is merged.
Before we merge this, let's wait for a confirmation that we're on the right track.

Replace AbstractTriangular by union

---

Project.toml
src/indexing.jl
test/matrix_multiply.jl

This fixes `mul!(@MArray([0.0]), Diagonal([1]), @MArray([-14691.819508873506]))` in line with the same change in getindex.

fix vector indexing

---

src/mapreduce.jl
src/traits.jl

A few nits from JET.jl: mostly just to reduce noise in future reports.
In `/src/mapreduce.jl` the issue is a missing default for a kwarg, in `/src/traits.jl` the issue is that `Val{L}` is not instantiated (i.e., ought to have been `Val{L}()`) and beyond that that there isn't even a `unroll_tuple(::Any, ::Val)` method to call.

small nits from JET report

---

.github/workflows/ci.yml
Project.toml
src/arraymath.jl
src/convert.jl
src/util.jl
test/check_bounds_no.jl
test/runtests.jl

Fixes the concrete issue in #1155.
Julia 1.9 favors concrete-eval over constant propagation.
Furthermore the effect system was powered up and [many `@pure` annotation were removed](https://github.com/JuliaLang/julia/pull/44776).
With `--check-bounds=no` [concrete-eval is disabled](https://github.com/JuliaLang/julia/blob/8419b5042690fda143f366d09e4b0ee3f275efc7/base/compiler/abstractinterpretation.jl#L804)
and we rely entirely on const-prop, which seems to struggle whithout the `@pure` annotation.
@aviatesk would it be feasible to consider the effects for directing const-prop? We have two situations
where the reliance on concrete-eval has shown itself to be problematic. GPU code with custom method-tables,
and `--check-bounds=no`. 
In Julia 1.10 [`@pure` is …

Mark typeintersect pure for Julia 1.9

---

Project.toml
src/convert.jl

Fixes #1148 by implementing @N5N3 's suggestion.

Avoid runtime static parameters inference during dynamic dispatch of `SVector{k}`

---

Project.toml
src/eigen.jl
test/eigen.jl

This PR significantly improves worst-case accuracy of eigenvalues in 2x2 symmetric and Hermitian eigendecomposition. For matrix `m1 = SA[1.6590891025248637 -2.7087777909606814e-7; -2.7087777909606814e-7 1.659089317183428]`, we had
```julia
julia> norm(m1 - Array(eigen(m1)))
2.706275120796337e-10
julia> @btime eigen($m1)
10.599 ns (0 allocations: 0 bytes)
```
and after this change:
```julia
julia> norm(m1 - Array(eigen(m1)))
1.1102224952296907e-16
julia> @btime eigen($m1)
10.842 ns (0 allocations: 0 bytes)
```
so it's slightly slower but much more accurate.

Improve accuracy of 2x2 symmetric/Hermitian eigendecomposition

---

Project.toml
src/linalg.jl
test/linalg.jl

Fixes #1135 by making the functionality introduced in #975 play nicer with arrays that contain `NaN` or `(±)Inf` elements. This removes an unexpected dependence of the return of `norm()` on the ordering of the elements in these cases, and also makes the results consistent with regular Julia arrays.
(Thanks to @rmkn85 for the help in tracing the cause of this one)
EDIT: fix typos

Fix norm of StaticArrays with non-finite elements

---

Project.toml
src/SMatrix.jl
src/SVector.jl

This makes calls to `zeros`, `ones`, `rand`, and friend default to `Float64`
similar to Base. This can be a source of type instability when used
in the single argument version, and it is not transparent as to why.
Making `Float64` the default eliminates this source of error for the user.
Closes: https://github.com/JuliaArrays/StaticArrays.jl/issues/1164

make `@SVector` and `@SMatrix` calls default to `Float64` to match Base

---

Project.toml
ext/StaticArraysStatisticsExt.jl
src/StaticArrays.jl
src/mapreduce.jl
test/svd.jl

I think this is a no-brainer. It doesn't cost anything in terms of functionality, but reduces package load time significantly on Julia v1.9+. One could still decide later on to remove this or solve this via fallbacks etc., see #1171.

Handle Statistics dep as Pkg extension

---

.github/workflows/ci.yml

Since v1 points to v1.9 now, we don't need the explicit test anymore. This PR changes it to the unreleased versions of v1.10

Test on Julia v1.10

---

src/precompile.jl

Fixes #1182 
Just disables these on v1.11.
Someone familiar with the issue should review and fix if appropriate.

disable precompiles that fail on julia v1.11

---

src/linalg.jl
test/linalg.jl

This PR special-cases the return-types of the `adjoint` and `transpose` for `SMatrix` and `MMatrix`. This isn't ideal, but currently Julia doesn't infer the return types of certain recursive calls with changing types, and this PR helps with type-inference in such cases.
An example (using this PR):
```julia
julia> S = SMatrix{3,2,SMatrix{1,2,Int,2},6}(fill(SMatrix{1,2,Int,2}(1:2), 6))
3×2 SMatrix{3, 2, SMatrix{1, 2, Int64, 2}, 6} with indices SOneTo(3)×SOneTo(2):
[1 2]  [1 2]
[1 2]  [1 2]
[1 2]  [1 2]
julia> @inferred adjoint(S)
2×3 SMatrix{2, 3, SMatrix{2, 1, Int64, 2}, 6} with indices SOneTo(2)×SOneTo(3):
[1; 2;;]  [1; 2;;]  [1; 2;;]
[1; 2;;]  [1; 2;;]  [1; 2;;]
```
Whereas, on master,
```julia
julia> @inferred adjoint(S)
ERROR: return type SMatrix{2, 3, SMatrix{2, 1, Int64, 2}, 6} does …
```

Improve type inference for adjoint/transpose of nested matrices

---

src/abstractarray.jl
test/abstractarray.jl

The idea of this PR is to make the fallback `similar` method less specific in the axes, to make it easier for packages to extend `similar` for custom array types without encountering ambiguities.
The way the fallback `similar` method is defined currently makes it tricky for custom array types to extend `similar` without running into ambiguities. For example, an array type defined as:
```julia
julia> struct CustomArray{T} <: AbstractVector{T}
sz :: Int
end
julia> Base.size(C::CustomArray) = (C.sz,)
julia> Base.getindex(C::CustomArray{T}, i::Int) where {T} = T(i)
julia> Base.similar(C::CustomArray, ::Type{T}, ax::Tuple{Vararg{Int}}) where {T} =
Array{T}(undef, ax)
julia> function Base.similar(C::CustomArray, ::Type{T}, ax::Tuple{Vararg{Union{Int, SOneTo, Base.OneTo{Int}}}}) where {T}
sz = …
```

Make fallback similar methods less specific in axes

---

Project.toml
src/eigen.jl
test/eigen.jl
test/initializers.jl

Fixes #956 by subtracting mean diagonal (draft because for now only for `A.uplo == 'U'`, see question below)
`a = SMatrix{2,2}((1.0, 1e-100, 1e-100, 1.0))`
Master (fast, but incorrect)
```julia
@btime eigen($a)
9.510 ns (0 allocations: 0 bytes)
eigen(a)
Eigen{Float64, Float64, SMatrix{2, 2, Float64, 4}, SVector{2, Float64}}
values:
2-element SVector{2, Float64} with indices SOneTo(2):
1.0
1.0
vectors:
2×2 SMatrix{2, 2, Float64, 4} with indices SOneTo(2)×SOneTo(2):
0.0  0.0
1.0  1.0
```
PR (slower, but correct)
```julia
julia> @btime eigen($a)
11.011 ns (0 allocations: 0 bytes)
julia> eigen(a)
Eigen{Float64, Float64, SMatrix{2, 2, Float64, 4}, SVector{2, Float64}}
values:
2-element SVector{2, Float64} with indices SOneTo(2):
1.0
1.0
vectors:
2×2 SMatrix{2, 2, Float64, 4} with indices …
```

Fix precision of 2x2 eigenvectors

---

src/abstractarray.jl
test/abstractarray.jl

fixes https://github.com/JuliaArrays/StaticArrays.jl/issues/1195
fixes https://github.com/apache/arrow-julia/issues/486
fixes https://github.com/JuliaArrays/StaticArrays.jl/issues/799
(apparently) fixes https://github.com/FluxML/Zygote.jl/issues/686

make similar mutable for non bits types

---

Project.toml
src/StaticArrays.jl
src/precompile.jl

Fixes #1184
Fixes #1182
Closes #1183
@timholy would you mind helping me figure out the commented out ones?

Move to PrecompileTools

---

docs/src/pages/api.md
docs/src/pages/quickstart.md

[`eye`](https://docs.julialang.org/en/v0.6/stdlib/arrays/#Base.eye) was removed in Julia v1.0. :wink:

Remove `eye` from the docs, update around `@SVector` and `@SMatrix` docs

---

test/runtests.jl
test/unbound_args.jl

This is now tested with Aqua.jl (#1212).

Remove tests for `unbound_args`

---

src/sort.jl

I inlined the implementations to the call sites which, remarkably, improves concision.

Stop using internals: `Base.copymutable` [NFC]

---

Project.toml
src/abstractarray.jl
src/broadcast.jl
test/abstractarray.jl
test/broadcast.jl

Currently, broadcasting with `StaticMatrixLike`-types does not always return `SMatrix` results:
```julia
julia> using StaticArrays, LinearAlgebra
julia> Symmetric(@SMatrix [1 2; 3 4]) .+ 1
2×2 Matrix{Int64}:
2  3
3  5
julia> Symmetric(@SMatrix [1 2; 3 4]) .+ @SVector [5, 6]
2×2 Matrix{Int64}:
6   7
8  10
julia> Symmetric(@SMatrix [1 2; 3 4]) .+ @SMatrix [5 6; 7 8]
2×2 SizedMatrix{2, 2, Int64, 2, Matrix{Int64}} with indices SOneTo(2)×SOneTo(2):
6   8
9  12
```
The PR fixes this by generalizing definitions of `BroadcastStyle`, `isstatic`, and `axes` to `StaticMatrixLike`:
```julia
julia> using StaticArrays, LinearAlgebra
julia> Symmetric(@SMatrix [1 2; 3 4]) .+ 1
2×2 SMatrix{2, 2, Int64, 4} with indices SOneTo(2)×SOneTo(2):
2  3
3  5
julia> Symmetric(@SMatrix [1 2; 3 4]) .+ @SVector [5, 6] …
```

Generalize broadcasting to `StaticMatrixLike`

---

Project.toml
ext/StaticArraysChainRulesCoreExt.jl
test/chainrules.jl

Based on the comment https://github.com/JuliaArrays/StaticArrays.jl/commit/91f4857cddbdec7fdbe32ea9f4ef7506ed2bc8b0#commitcomment-135109496
@Larbino1 do you have some other tests to try it on?

Handle the rrule for SVector{}(....)

---

Project.toml
ext/StaticArraysChainRulesCoreExt.jl
test/chainrules.jl

Fixes https://github.com/JuliaArrays/StaticArrays.jl/commit/91f4857cddbdec7fdbe32ea9f4ef7506ed2bc8b0#commitcomment-135247113
Main problem was type instability coming from storing a DataType. Added a test using JLArrays for the patch

Fix Type Instability in SArray Projection

---

test/arraymath.jl

On Julia nightly,
```julia
julia> subtypes(AbstractFloat)
5-element Vector{Any}:
BigFloat
Core.BFloat16
Float16
Float32
Float64
```
and `Core.BFloat16` does not have `one` defined for itself, which was leading to test failures. It's better to be explicit in the types that we test against, which are known to work.

Test `arithmetic_closure` against concrete types

---

.gitignore

Julia v1.11 supports version-specific Manifest files, so it's better to ignore these files as well in `.gitignore`

Ignore versioned manifest files

---

.github/workflows/ci.yml

Now that v1 points to v1.10, the explicit tests on v1.10 are redundant

Remove duplicate tests on v1.10

---

src/SizedArray.jl
test/SizedArray.jl

These changes should address some of the breakages related to `pointer` on julia nightly that are reported in https://github.com/JuliaLang/julia/issues/51962

Specialize `cconvert` instead of `unsafe_convert`

---

src/abstractarray.jl
test/abstractarray.jl

After this,
```julia
julia> zeros(SOneTo(4))
4-element SVector{4, Float64} with indices SOneTo(4):
0.0
0.0
0.0
0.0
```
and similarly, `ones` and `fill` also return `SArray`s.

Specialize `zeros`/`ones`/`fill` for `SOneTo`

---

src/svd.jl

Following the suggestion in https://github.com/JuliaLang/julia/issues/53038#issuecomment-1913939448
This should help with the `svd` regression on Julia nightly, as reported in https://github.com/JuliaLang/julia/issues/53038

Inline `svd` to enable constant-propagation of `full`

---

Project.toml
src/convert.jl

Following #1244 I just went ahead with this small change.
This should improve GPU-compatibility.
Original discussion: https://discourse.julialang.org/t/problems-with-linearalgebra-functions-within-kernelabstractions-and-cuda/97566/5

Force specialization of dimension_mismatch_fail() on type argument.

---

Project.toml
src/FieldArray.jl
test/FieldMatrix.jl
test/FieldVector.jl

This PR was originally posted to [`StaticArraysCore.jl`](https://github.com/JuliaArrays/StaticArraysCore.jl/pull/25), but was moved to here because `StaticArraysCore` lacks the method definitions necessary to make this `NamedTuple` functionality work. 
I have found `NamedTuple` to be a performant way to initialize `FieldArray` subtypes. See, for example, the following code in [`AstrodynamicalModels.jl`](https://github.com/cadojo/AstrodynamicalModels.jl/blob/8c811923c2d56b7927bf4c62acc2fbfa1bcd91d4/src/AstrodynamicalModels.jl#L107). I think it may also be useful sometimes to go in reverse: convert a `FieldArray` subtype back into a `NamedTuple`. **Do you agree this may be useful, and without undesirable side effects?** I got this idea from `SciML`'s [`Base.NamedTuple` …

NamedTuple constructor support for FieldArray subtypes

---

Project.toml
docs/src/pages/api.md
src/SHermitianCompact.jl
src/SOneTo.jl
src/SUnitRange.jl
src/abstractarray.jl
src/convert.jl
src/indexing.jl
src/traits.jl

I think it will be much easier to track potential performance regressions when pure removal is split into a few steps. This is the first one.

Remove some uses of `@pure`

---

Project.toml
src/SHermitianCompact.jl
test/SHermitianCompact.jl

This pr adds some methods to dispatch complex scalar multiplication/division with `SHermitianCompact` to a correct method using `SMatrix`. Tests are also added. For other details see #1263

Complex multiplication with SHermitianCompact

---

src/SHermitianCompact.jl
test/SHermitianCompact.jl

As mentioned in #1263, the `SHermitianCompact` type can represent matrices which are neither Hermitian nor symmetric, so this pr fixes the definitions of `ishermitian` and `issymmetric` to capture this and adds tests to verify the logic on some of these unusual cases. I think this would be preferable to making `SHermitianCompact` guarantee that it is in fact Hermitian, i.e. by always returning real values on the diagonal, because the latter would be breaking.

improved definitions of ishermitian/issymmetric

---

Project.toml
src/inv.jl
test/inv.jl

This pr refactors the `inv` code so that `inv(::StaticArrays.LU)` behaves like `inv(::LinearAlgebra.LU)`, allowing the construction of the inverse from the LU factorization. I'm not sure if I handled inlining correctly and I would be happy to implement any feedback.

refactor inv to also work for lu

---

src/StaticArrays.jl

This is not being used anywhere in the package, and `StaticArraysCore` now uses the `Base` function instead of defining their own. This means precompilation is currently broken for this package without removing this import.

Don't import require_one_based_indexing from StaticArraysCore

---

.github/workflows/Invalidations.yml
Project.toml
src/mapreduce.jl
test/mapreduce.jl
test/runtests.jl

Allows StaticArrays' `count` implementation to take an `init` kwarg, just as `Base.count` (since Julia v1.6).
Also bumps StaticArrays to v1.9.8, to enable releasing the fix.
EDIT: Updated to also add `init` to `prod` and `sum`, fixing #1119 in the process.

Let `count`, `sum`, and `prod` take an `init` kwarg

---

Project.toml
src/linalg.jl
test/unitful.jl

This is #1125 and #1128 for general p-norms, where $p\neq 0,2,\infty$. Before:
```julia
julia> norm(SVector(1.0, 2.0)*u"m", 1)
ERROR: DimensionError: 0.0 and 3.0 m are not dimensionally compatible.
Stacktrace:
[1] _lt
@ ~/.julia/packages/Unitful/dHMk1/src/quantities.jl:250 [inlined]
[2] <(x::Quantity{Float64, NoDims, Unitful.FreeUnits{…}}, y::Quantity{Float64, 𝐋, Unitful.FreeUnits{…}})
@ Unitful ~/.julia/packages/Unitful/dHMk1/src/quantities.jl:240
[3] <(x::Int64, y::Quantity{Float64, 𝐋, Unitful.FreeUnits{(m,), 𝐋, nothing}})
@ Unitful ~/.julia/packages/Unitful/dHMk1/src/quantities.jl:242
[4] macro expansion
@ ~/.julia/dev/StaticArrays/src/linalg.jl:331 [inlined]
[5] _norm
@ ~/.julia/dev/StaticArrays/src/linalg.jl:311 [inlined]
[6] norm(a::SVector{2, Quantity{Float64, 𝐋, …
```

Fix p-norm for unitful quantities

---

Project.toml
ext/StaticArraysStatisticsExt.jl
src/sort.jl
test/sort.jl

This implements `Statistics.median` based on the existing bitonic
sorting, avoiding unnecessary allocation.
While it is generally suboptimal to sort the whole array, the compiler
manages to skip some branches since only the middle element(s) are used.
Thus `median` is generally faster than `sort`.
Using a dedicated median selection network could yield better
performance and might be considered for future improvement.

implement Statistics.median

---

src/matrix_multiply.jl

`a` isn't defined globally, thus it should not be interpolated.

fix `mul_generic` implementation

---

Project.toml
src/expm.jl
test/expm.jl

Fix #1295 
Appreciate if you can review this @mikmoore.

Fix `exp` of `SMatrix` with large entries #1295

---

src/SDiagonal.jl

JET complained about this method when analyzing my package and it's a
fairly easy fix

stop pirating `size(::Type{Union{}})`

---

src/mapreduce.jl
test/mapreduce.jl

Julia v1.12 introduces the 2-term `map!`, where the source and the destination are identical. Currently, this package errors without a third term, as it can't find the source array. This PR ensures that the method works for `StaticArrays`s.
After this,
```julia
julia> M = MVector(1,3,4)
3-element MVector{3, Int64} with indices SOneTo(3):
1
3
4
julia> map!(x->x^2, M)
3-element MVector{3, Int64} with indices SOneTo(3):
1
9
16
julia> M
3-element MVector{3, Int64} with indices SOneTo(3):
1
9
16
```

Specialize `map!(f, array)`

---

src/abstractarray.jl
test/indexing.jl

As of the latest release, trying to `view` into an `SArray` with an eltype of `Any` such that the view also returns an `SArray` would wrap the returned array in a scalar. `_maybewrapscalar` assumes that if the `eltype` of the array matches the type of the view, it must be a scalar view. This assumption breaks down when the `eltype` is `Any`. MWE:
```julia
julia> A = SVector{4, Any}(1,2,3,4)
julia> I = SVector{2}(3, 1)
julia> view(A, I)
Scalar{Any}((Any[3, 1],))
julia> view(A, [3, 1])
2-element view(::SVector{4, Any}, [3, 1]) with eltype Any:
3
1
```
I've verified that all the added tests fail on the latest release and pass with this PR.

fix: fix n-dimensional `view` into n-dimensional `SArray` with `Any` eltype
